"""Type stubs for pandas.api.types."""

from typing import Any

def is_integer_dtype(arr_or_dtype: Any) -> bool: ...

def is_float_dtype(arr_or_dtype: Any) -> bool: ...

def is_string_dtype(arr_or_dtype: Any) -> bool: ...

def is_bool_dtype(arr_or_dtype: Any) -> bool: ...

def is_numeric_dtype(arr_or_dtype: Any) -> bool: ...

def is_datetime64_any_dtype(arr_or_dtype: Any) -> bool: ...

def is_object_dtype(arr_or_dtype: Any) -> bool: ...

