extends: ../base.yaml

pipeline:
  name: activity
  entity: activity

sources:
  chembl:
    enabled: true
    base_url: "https://www.ebi.ac.uk/chembl/api/data"
    batch_size: 25
    max_url_length: 2000

determinism:
  hash_algorithm: "sha256"
  float_precision: 6
  datetime_format: "iso8601"
  sort:
    by: ["activity_id"]
    ascending: [true]

qc:
  enabled: true
  severity_threshold: error
  duplicate_check:
    enabled: true
    field: "activity_id"
    threshold: 0
  thresholds:
    duplicates: 0
    null_rate_critical: 0.3
    invalid_units: 0

