extends: ../base.yaml

pipeline:
  name: assay
  entity: assay

sources:
  chembl:
    enabled: true
    base_url: "https://www.ebi.ac.uk/chembl/api/data"
    batch_size: 20
    max_url_length: 2000

determinism:
  hash_algorithm: "sha256"
  float_precision: 6
  datetime_format: "iso8601"
  sort:
    by: ["assay_chembl_id", "row_subtype"]
    ascending: [true, true, true]

qc:
  enabled: true
  severity_threshold: warning

