extends:
  - ../base.yaml
  - ../includes/determinism_defaults.yaml
  - ../includes/chembl_source.yaml

pipeline:
  name: assay
  entity: assay

sources:
  chembl:
    batch_size: 20
    headers:
      User-Agent: "bioetl-assay-pipeline/1.0"

determinism:
  sort:
    by: ["assay_chembl_id", "row_subtype"]
    ascending: [true, true]
  column_order: [
    "index", "hash_row", "hash_business_key", "pipeline_version", "source_system", "chembl_release", "extracted_at",
    "assay_chembl_id", "assay_type", "assay_category", "assay_cell_type", "assay_classifications", "assay_group",
    "assay_organism", "assay_parameters_json", "assay_strain", "assay_subcellular_fraction", "assay_tax_id",
    "assay_test_type", "assay_tissue", "assay_type_description", "bao_format", "bao_label", "bao_endpoint",
    "cell_chembl_id", "confidence_description", "confidence_score", "assay_description", "document_chembl_id",
    "relationship_description", "relationship_type", "src_assay_id", "src_id", "target_chembl_id", "tissue_chembl_id",
    "variant_sequence_json", "pref_name", "organism", "target_type", "species_group_flag", "tax_id", "component_count",
    "assay_param_type", "assay_param_relation", "assay_param_value", "assay_param_units", "assay_param_text_value",
    "assay_param_standard_type", "assay_param_standard_value", "assay_param_standard_units", "assay_class_id",
    "assay_class_bao_id", "assay_class_type", "assay_class_l1", "assay_class_l2", "assay_class_l3",
    "assay_class_description", "variant_id", "variant_base_accession", "variant_mutation", "variant_sequence",
    "variant_accession_reported", "fallback_reason", "fallback_error_type", "fallback_error_code",
    "fallback_error_message", "fallback_http_status", "fallback_retry_after_sec", "fallback_attempt", "fallback_timestamp"
  ]

qc:
  enabled: true
  severity_threshold: warning
  thresholds:
    null_rate_critical: 0.3
    duplicates: 0
    fallback_usage_rate: 0.1
