extends:
  - ../base.yaml
  - ../includes/chembl_source.yaml

pipeline:
  name: target
  entity: target

http:
  chembl:
    timeout_sec: 45.0
    connect_timeout_sec: 10.0
    read_timeout_sec: 45.0
    retries:
      total: 5
      backoff_multiplier: 2.0
      backoff_max: 120.0
      statuses: [404, 408, 409, 425, 429, 500, 502, 503, 504]
    rate_limit:
      max_calls: 12
      period: 1.0
    rate_limit_jitter: true
    headers:
      Accept: "application/json"
      User-Agent: "bioetl-target-pipeline/1.0"
  uniprot:
    timeout_sec: 60.0
    connect_timeout_sec: 10.0
    read_timeout_sec: 60.0
    retries:
      total: 4
      backoff_multiplier: 2.0
      backoff_max: 90.0
      statuses: [404, 408, 409, 425, 429, 500, 502, 503, 504]
    rate_limit:
      max_calls: 3
      period: 1.0
    rate_limit_jitter: true
    headers:
      Accept: "application/json"
      User-Agent: "bioetl-target-pipeline/1.0"
  uniprot_idmapping:
    timeout_sec: 60.0
    connect_timeout_sec: 10.0
    read_timeout_sec: 60.0
    retries:
      total: 4
      backoff_multiplier: 2.0
      backoff_max: 90.0
      statuses: [404, 408, 409, 425, 429, 500, 502, 503, 504]
    rate_limit:
      max_calls: 2
      period: 1.0
    rate_limit_jitter: true
    headers:
      Accept: "application/json"
      User-Agent: "bioetl-target-pipeline/1.0"
  uniprot_orthologs:
    timeout_sec: 60.0
    connect_timeout_sec: 10.0
    read_timeout_sec: 60.0
    retries:
      total: 4
      backoff_multiplier: 2.0
      backoff_max: 90.0
      statuses: [404, 408, 409, 425, 429, 500, 502, 503, 504]
    rate_limit:
      max_calls: 2
      period: 1.0
    rate_limit_jitter: true
    headers:
      Accept: "application/json"
      User-Agent: "bioetl-target-pipeline/1.0"
  iuphar:
    timeout_sec: 45.0
    connect_timeout_sec: 10.0
    read_timeout_sec: 45.0
    retries:
      total: 4
      backoff_multiplier: 2.0
      backoff_max: 60.0
      statuses: [404, 408, 409, 425, 429, 500, 502, 503, 504]
    rate_limit:
      max_calls: 6
      period: 1.0
    rate_limit_jitter: true
    headers:
      Accept: "application/json"
      User-Agent: "bioetl-target-pipeline/1.0"

sources:
  chembl:
    batch_size: 25
    headers:
      User-Agent: "bioetl-target-pipeline/1.0"
    http_profile: chembl
    stage: primary
    cache_enabled: true
    cache_ttl: 43200
    cache_maxsize: 4096
    fallback_strategies: ["cache", "network"]
    circuit_breaker:
      failure_threshold: 5
      timeout_sec: 90.0
  uniprot:
    enabled: true
    base_url: "https://rest.uniprot.org/uniprotkb"
    http_profile: uniprot
    stage: enrichment
    rate_limit:
      max_calls: 3
      period: 1.0
    cache_enabled: true
    cache_ttl: 21600
  uniprot_idmapping:
    enabled: true
    base_url: "https://rest.uniprot.org/idmapping"
    http_profile: uniprot_idmapping
    stage: enrichment
    cache_enabled: true
    cache_ttl: 21600
  uniprot_orthologs:
    enabled: false
    base_url: "https://rest.uniprot.org/uniprotkb/stream"
    http_profile: uniprot_orthologs
    stage: optional
  iuphar:
    enabled: true
    base_url: "https://www.guidetopharmacology.org/services"
    http_profile: iuphar
    stage: enrichment
    api_key: "${IUPHAR_API_KEY}"
    headers:
      x-api-key: "${IUPHAR_API_KEY}"
    rate_limit:
      max_calls: 6
      period: 1.0
    cache_enabled: true
    cache_ttl: 14400

determinism:
  hash_algorithm: "sha256"
  float_precision: 6
  datetime_format: "iso8601"
  sort:
    by: ["target_chembl_id"]
    ascending: [true]
  column_order: [
    "target_chembl_id", "isoform_ids", "isoform_names", "isoforms", "pref_name", "target_type", "organism", "tax_id",
    "gene_symbol", "hgnc_id", "lineage", "primaryAccession", "target_names", "target_uniprot_id", "organism_chembl",
    "species_group_flag", "target_components", "protein_classifications", "cross_references", "target_names_chembl",
    "pH_dependence", "pH_dependence_chembl", "target_organism", "target_tax_id", "target_uniprot_accession",
    "target_isoform", "isoform_ids_chembl", "isoform_names_chembl", "isoforms_chembl", "uniprot_accession",
    "uniprot_id_primary", "uniprot_ids_all", "isoform_count", "has_alternative_products", "has_uniprot", "has_iuphar",
    "iuphar_type", "iuphar_class", "iuphar_subclass", "data_origin", "pipeline_version", "source_system",
    "chembl_release", "extracted_at", "hash_business_key", "hash_row", "index"
  ]

qc:
  enabled: true
  severity_threshold: warning
  thresholds:
    enrichment_success.uniprot:
      min: 0.8
      severity: warning
    enrichment_success.iuphar:
      min: 0.6
      severity: warning
    fallback_usage_rate:
      max: 0.1
      severity: info
  stage_expectations:
    chembl: true
    uniprot: true
    uniprot_idmapping: true
    iuphar: true
  enrichments:
    uniprot: 0.8
    iuphar: 0.1

materialization:
  bronze: "data/output/target/targets_bronze.parquet"
  silver: "data/output/target/targets_silver.parquet"
  gold: "data/output/target/targets_final.parquet"
  qc_report: "data/output/target/targets_qc.csv"
  checkpoints:
    chembl: "data/output/target/checkpoints/chembl_targets.json"
    enrichment: "data/output/target/checkpoints/targets_enrichment.json"

fallbacks:
  enabled: true
  prefer_cache: true
  allow_partial_materialization: true
  strategies:
    - cache
    - network
    - offline
  partial_retry_max: 2
  use_materialized_outputs: true
  circuit_breaker:
    failure_threshold: 5
    timeout_sec: 90.0

