extends: ../base.yaml

pipeline:
  name: testitem
  entity: testitem

sources:
  chembl:
    enabled: true
    base_url: "https://www.ebi.ac.uk/chembl/api/data"
    batch_size: 25
    max_url_length: 2000
  pubchem:
    enabled: false  # PubChem enrichment optional
    base_url: "https://pubchem.ncbi.nlm.nih.gov/rest/pug"
    batch_size: 100

determinism:
  sort:
    by: ["molecule_chembl_id"]
    ascending: [true]

qc:
  enabled: true
  severity_threshold: warning

