from typing import Any, MutableMapping

class Response:
    status_code: int
    headers: MutableMapping[str, str]
    text: str
    content: bytes
    url: str

    def json(self, **kwargs: Any) -> Any: ...
    def raise_for_status(self) -> None: ...


class Session:
    headers: MutableMapping[str, str]

    def __init__(self) -> None: ...
    def request(self, method: str, url: str, **kwargs: Any) -> Response: ...
    def get(self, url: str, **kwargs: Any) -> Response: ...
    def post(self, url: str, **kwargs: Any) -> Response: ...
    def close(self) -> None: ...


def get(url: str, **kwargs: Any) -> Response: ...
def post(url: str, **kwargs: Any) -> Response: ...

def Request(method: str, url: str, **kwargs: Any) -> Any: ...

from . import exceptions as exceptions
