# Safety policy configuration
# This file defines how safety handles security vulnerabilities

# Ignore specific vulnerabilities by CVE ID
ignore:
  # Example: ignore specific CVE if it doesn't affect our use case
  # - "CVE-2023-12345"

# Ignore vulnerabilities by package and version
ignore_versions:
  # Example: ignore specific version of a package
  # pandas:
  #   - "1.5.0"

# Set minimum confidence level for vulnerability detection
confidence: high

# Set minimum severity level for vulnerability detection  
severity: medium

# Include development dependencies in scan
include_dev: true

# Output format for reports
output_format: json
