"""Фасад клиентского слоя BioETL."""

from __future__ import annotations

from bioetl.clients.base import (  # noqa: F401
    FACTORIES,
    ClientFactory,
    ClientProtocol,
    ConfigurationError,
    ConnectionError,
    DataProviderProtocol,
    HTTPError,
    Page,
    PageStream,
    PaginationError,
    PaginationParams,
    ProviderError,
    RecordStream,
    RequestContext,
    RequestException,
    RetryOptions,
    SupportsBatch,
    SupportsSearch,
    Timeout,
    TransportOptions,
    get_factory,
    register_domain_factories,
    register_factory,
)
from bioetl.clients.chembl import (  # noqa: F401
    BaseChemblClient,
    ChemblActivityClient,
    ChemblAssayClient,
    ChemblDocumentClient,
    ChemblEntityClientFactory,
    ChemblEntityClientFactoryConfig,
    ChemblEntityClientFactoryProtocol,
    ChemblEntityClientProtocol,
    ChemblTargetClient,
    ChemblTestItemClient,
)
from bioetl.clients.chembl.factories import (  # noqa: F401
    default_chembl_factory,
    make_chembl_client,
)
from bioetl.clients.factories import (  # noqa: F401
    ENRICHER_ALLOWED_ENTITIES,
    ClientMethodStrategy,
    EnricherApiConfig,
    EnricherApiFactory,
    EnricherClientFactory,
    EnricherEntity,
    EnricherFacade,
    EnrichmentStrategy,
    NULL_ENRICHER_FACTORY,
    NullEnricherFacade,
    StrategyRegistry,
    build_enricher_facade,
)
from bioetl.clients.providers import (  # noqa: F401
    BaseDataProvider,
    CrossrefClient,
    OpenAlexClient,
    PubChemClient,
    PubmedClient,
    SemanticScholarClient,
    UniProtClient,
    create_route_provider_class,
)
from bioetl.clients.providers.routes import (  # noqa: F401
    BaseEnricherClient,
    DeprecatedAliasMixin,
    EnricherClientOptions,
    EnricherClientProtocol,
    RouteConfig,
    RouteEnricherMixin,
    RouteProviderBase,
    UnifiedProviderAdapter,
)
from bioetl.clients.utils.common import *  # noqa: F401,F403

__all__ = [
    # Base client plumbing
    "ConnectionError",
    "ProviderError",
    "PaginationError",
    "ConfigurationError",
    "HTTPError",
    "RequestException",
    "Timeout",
    "ClientProtocol",
    "ClientFactory",
    "FACTORIES",
    "register_factory",
    "register_domain_factories",
    "get_factory",
    "BaseDataProvider",
    "DataProviderProtocol",
    "SupportsBatch",
    "SupportsSearch",
    "PaginationParams",
    "RequestContext",
    "RecordStream",
    "Page",
    "PageStream",
    "TransportOptions",
    "RetryOptions",
    # Chembl clients
    "BaseChemblClient",
    "ChemblActivityClient",
    "ChemblAssayClient",
    "ChemblDocumentClient",
    "ChemblTargetClient",
    "ChemblTestItemClient",
    "ChemblEntityClientFactory",
    "ChemblEntityClientFactoryConfig",
    "ChemblEntityClientFactoryProtocol",
    "ChemblEntityClientProtocol",
    "make_chembl_client",
    "default_chembl_factory",
    # Enricher base
    "BaseEnricherClient",
    "DeprecatedAliasMixin",
    "EnricherClientOptions",
    "EnricherClientProtocol",
    "RouteConfig",
    "RouteEnricherMixin",
    "RouteProviderBase",
    "UnifiedProviderAdapter",
    "create_route_provider_class",
    # Enricher factory & facade
    "ClientMethodStrategy",
    "EnricherApiConfig",
    "EnricherApiFactory",
    "EnricherClientFactory",
    "EnricherEntity",
    "ENRICHER_ALLOWED_ENTITIES",
    "NULL_ENRICHER_FACTORY",
    "EnricherFacade",
    "EnrichmentStrategy",
    "NullEnricherFacade",
    "StrategyRegistry",
    "build_enricher_facade",
    # Providers
    "CrossrefClient",
    "OpenAlexClient",
    "PubChemClient",
    "PubmedClient",
    "SemanticScholarClient",
    "UniProtClient",
]
