"""ChEMBL activity schema with full column set for enrichment."""

from __future__ import annotations

import pandera.pandas as pa
import pandas as pd

# Full column list from activity_chembl.yaml config
_CHEMBL_ACTIVITY_COLUMNS = [
    "activity_id",
    "row_subtype", 
    "row_index",
    "assay_chembl_id",
    "assay_type",
    "assay_description",
    "assay_organism",
    "assay_tax_id",
    "testitem_chembl_id",
    "molecule_chembl_id",
    "parent_molecule_chembl_id",
    "molecule_pref_name",
    "target_chembl_id",
    "target_pref_name",
    "document_chembl_id",
    "record_id",
    "src_id",
    "type",
    "relation",
    "value",
    "units",
    "standard_type",
    "standard_relation",
    "standard_value",
    "standard_units",
    "standard_flag",
    "pchembl_value",
    "uo_units",
    "qudt_units",
    "activity_comment",
    "bao_endpoint",
    "bao_format",
    "bao_label",
    "canonical_smiles",
    "ligand_efficiency",
    "target_organism",
    "target_tax_id",
    "data_validity_comment",
    "data_validity_description",
    "potential_duplicate",
    "activity_properties",
    "compound_key",
    "compound_name",
    "curated",
    "removed",
    "business_key",
    "business_key_hash",
    "row_hash",
]

ChEMBLActivitySchema = pa.DataFrameSchema(
    {
        "activity_id": pa.Column(pa.String, nullable=False),
        "row_subtype": pa.Column(pa.String, nullable=True),
        "row_index": pa.Column(pd.Int64Dtype(), nullable=True),
        "assay_chembl_id": pa.Column(pa.String, nullable=False),
        "assay_type": pa.Column(pa.String, nullable=True),
        "assay_description": pa.Column(pa.String, nullable=True),
        "assay_organism": pa.Column(pa.String, nullable=True),
        "assay_tax_id": pa.Column(pa.String, nullable=True),
        "testitem_chembl_id": pa.Column(pa.String, nullable=True),
        "molecule_chembl_id": pa.Column(pa.String, nullable=True),
        "parent_molecule_chembl_id": pa.Column(pa.String, nullable=True),
        "molecule_pref_name": pa.Column(pa.String, nullable=True),
        "target_chembl_id": pa.Column(pa.String, nullable=True),
        "target_pref_name": pa.Column(pa.String, nullable=True),
        "document_chembl_id": pa.Column(pa.String, nullable=True),
        "record_id": pa.Column(pa.String, nullable=True),
        "src_id": pa.Column(pa.String, nullable=True),
        "type": pa.Column(pa.String, nullable=True),
        "relation": pa.Column(pa.String, nullable=True),
        "value": pa.Column(pa.Float, nullable=True),
        "units": pa.Column(pa.String, nullable=True),
        "standard_type": pa.Column(pa.String, nullable=True),
        "standard_relation": pa.Column(pa.String, nullable=True),
        "standard_value": pa.Column(pa.Float, nullable=True),
        "standard_units": pa.Column(pa.String, nullable=True),
        "standard_flag": pa.Column(pa.Bool, nullable=True),
        "pchembl_value": pa.Column(pa.Float, nullable=True),
        "uo_units": pa.Column(pa.String, nullable=True),
        "qudt_units": pa.Column(pa.String, nullable=True),
        "activity_comment": pa.Column(pa.String, nullable=True),
        "bao_endpoint": pa.Column(pa.String, nullable=True),
        "bao_format": pa.Column(pa.String, nullable=True),
        "bao_label": pa.Column(pa.String, nullable=True),
        "canonical_smiles": pa.Column(pa.String, nullable=True),
        "ligand_efficiency": pa.Column(pa.String, nullable=True),
        "target_organism": pa.Column(pa.String, nullable=True),
        "target_tax_id": pa.Column(pa.String, nullable=True),
        "data_validity_comment": pa.Column(pa.String, nullable=True),
        "data_validity_description": pa.Column(pa.String, nullable=True),
        "potential_duplicate": pa.Column(pa.Bool, nullable=True),
        "activity_properties": pa.Column(pa.String, nullable=True),
        "compound_key": pa.Column(pa.String, nullable=True),
        "compound_name": pa.Column(pa.String, nullable=True),
        "curated": pa.Column(pa.Bool, nullable=True),
        "removed": pa.Column(pa.Bool, nullable=True),
        "business_key": pa.Column(pa.String, nullable=False),
        "business_key_hash": pa.Column(pa.String, nullable=False),
        "row_hash": pa.Column(pa.String, nullable=False),
    },
    strict=True,
    ordered=True,
    coerce=True,
    name="ChEMBLActivitySchema",
)

ChEMBLActivityColumns = tuple(_CHEMBL_ACTIVITY_COLUMNS)

__all__ = ["ChEMBLActivitySchema", "ChEMBLActivityColumns"]
