"""Type stubs for hypothesis.strategies."""

from typing import Any

def integers(min_value: int | None = ..., max_value: int | None = ...) -> Any: ...

def floats(min_value: float | None = ..., max_value: float | None = ...) -> Any: ...

def text(alphabet: Any = ..., min_size: int | None = ..., max_size: int | None = ...) -> Any: ...

def lists(elements: Any, min_size: int | None = ..., max_size: int | None = ...) -> Any: ...

def dictionaries(keys: Any, values: Any, min_size: int | None = ..., max_size: int | None = ...) -> Any: ...

def sampled_from(elements: Any) -> Any: ...

def one_of(*args: Any) -> Any: ...

def just(value: Any) -> Any: ...

def none() -> Any: ...

def booleans() -> Any: ...

