extends:
  - ../base.yaml
  - ../includes/determinism.yaml
  - ../includes/chembl_source.yaml

pipeline:
  name: testitem
  entity: testitem
  version: "1.0.0"

materialization:
  pipeline_subdir: "testitem"

sources:
  chembl:
    enabled: true
    batch_size: 25
    max_url_length: 2000
    headers:
      User-Agent: "bioetl-testitem-pipeline/1.0"

determinism:
  sort:
    by: ["testitem_id"]
    ascending: [true]
  column_order:
    - "index"
    - "hash_row"
    - "hash_business_key"
    - "pipeline_version"
    - "source_system"
    - "chembl_release"
    - "extracted_at"
    - "testitem_id"
    - "pref_name"
    - "molecule_type"
    - "max_phase"
    - "first_approval"
    - "first_in_class"

qc:
  enabled: true
  severity_threshold: warning
  thresholds:
    null_rate_critical: 0.3
    duplicates: 0

