from __future__ import annotations

import pandera as pa

_HASH = pa.Check.str_length(min_value=64, max_value=64)


def activity_schema() -> pa.DataFrameSchema:
    return pa.DataFrameSchema(
        {
            "activity_id": pa.Column(pa.Int64, nullable=False, checks=pa.Check.ge(0)),
            "row_subtype": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "row_index": pa.Column(pa.Int64, nullable=False, checks=pa.Check.ge(0)),
            "assay_chembl_id": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "testitem_chembl_id": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "molecule_chembl_id": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "target_chembl_id": pa.Column(pa.String, nullable=True, required=False),
            "document_chembl_id": pa.Column(pa.String, nullable=True, required=False),
            "load_meta_id": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "hash_business_key": pa.Column(pa.String, nullable=True, required=False, checks=_HASH),
            "hash_row": pa.Column(pa.String, nullable=False, checks=_HASH),
            "compound_key": pa.Column(pa.String, nullable=True, required=False),
            "compound_name": pa.Column(pa.String, nullable=True, required=False),
            "curated": pa.Column(pa.Bool, nullable=True, required=False),
            "removed": pa.Column(pa.Bool, nullable=True, required=False),
            "type": pa.Column(pa.String, nullable=True, required=False),
            "relation": pa.Column(pa.String, nullable=True, required=False),
            "value": pa.Column(pa.Float64, nullable=True, required=False),
            "units": pa.Column(pa.String, nullable=True, required=False),
            "standard_type": pa.Column(pa.String, nullable=True, required=False),
            "standard_relation": pa.Column(pa.String, nullable=True, required=False),
            "standard_value": pa.Column(pa.Float64, nullable=True, required=False),
            "standard_upper_value": pa.Column(pa.Float64, nullable=True, required=False),
            "standard_units": pa.Column(pa.String, nullable=True, required=False),
            "standard_text_value": pa.Column(pa.String, nullable=True, required=False),
            "standard_flag": pa.Column(pa.Int64, nullable=True, required=False),
            "upper_value": pa.Column(pa.Float64, nullable=True, required=False),
            "lower_value": pa.Column(pa.Float64, nullable=True, required=False),
            "pchembl_value": pa.Column(pa.Float64, nullable=True, required=False),
            "uo_units": pa.Column(pa.String, nullable=True, required=False),
            "qudt_units": pa.Column(pa.String, nullable=True, required=False),
            "text_value": pa.Column(pa.String, nullable=True, required=False),
            "data_validity_comment": pa.Column(pa.String, nullable=True, required=False),
            "data_validity_description": pa.Column(pa.String, nullable=True, required=False),
            "potential_duplicate": pa.Column(pa.Bool, nullable=True, required=False),
            "canonical_smiles": pa.Column(pa.String, nullable=True, required=False),
            "ligand_efficiency": pa.Column(pa.Object, nullable=True, required=False),
            "activity_properties": pa.Column(pa.Object, nullable=True, required=False),
            "assay_type": pa.Column(pa.String, nullable=True, required=False),
            "assay_description": pa.Column(pa.String, nullable=True, required=False),
            "assay_organism": pa.Column(pa.String, nullable=True, required=False),
            "assay_tax_id": pa.Column(pa.Int64, nullable=True, required=False),
            "target_pref_name": pa.Column(pa.String, nullable=True, required=False),
            "target_organism": pa.Column(pa.String, nullable=True, required=False),
            "target_tax_id": pa.Column(pa.Int64, nullable=True, required=False),
        },
        coerce=True,
        strict=False,
    )


def assays_schema() -> pa.DataFrameSchema:
    return pa.DataFrameSchema(
        {
            "assay_chembl_id": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "row_subtype": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "row_index": pa.Column(pa.Int64, nullable=False, checks=pa.Check.ge(0)),
            "load_meta_id": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "hash_business_key": pa.Column(pa.String, nullable=False, checks=_HASH),
            "hash_row": pa.Column(pa.String, nullable=False, checks=_HASH),
            "description": pa.Column(pa.String, nullable=True, required=False),
            "assay_type": pa.Column(pa.String, nullable=True, required=False),
            "assay_type_description": pa.Column(pa.String, nullable=True, required=False),
            "assay_test_type": pa.Column(pa.String, nullable=True, required=False),
            "assay_category": pa.Column(pa.String, nullable=True, required=False),
            "assay_organism": pa.Column(pa.String, nullable=True, required=False),
            "assay_tax_id": pa.Column(pa.Int64, nullable=True, required=False),
            "assay_strain": pa.Column(pa.String, nullable=True, required=False),
            "assay_tissue": pa.Column(pa.String, nullable=True, required=False),
            "assay_cell_type": pa.Column(pa.String, nullable=True, required=False),
            "assay_subcellular_fraction": pa.Column(pa.String, nullable=True, required=False),
            "target_chembl_id": pa.Column(pa.String, nullable=True, required=False),
            "document_chembl_id": pa.Column(pa.String, nullable=True, required=False),
            "src_id": pa.Column(pa.Int64, nullable=True, required=False),
            "src_assay_id": pa.Column(pa.String, nullable=True, required=False),
            "cell_chembl_id": pa.Column(pa.String, nullable=True, required=False),
            "tissue_chembl_id": pa.Column(pa.String, nullable=True, required=False),
            "assay_group": pa.Column(pa.String, nullable=True, required=False),
            "confidence_score": pa.Column(pa.Int64, nullable=True, required=False),
            "confidence_description": pa.Column(pa.String, nullable=True, required=False),
            "assay_classifications": pa.Column(pa.Object, nullable=True, required=False),
            "assay_parameters": pa.Column(pa.Object, nullable=True, required=False),
            "assay_class_id": pa.Column(pa.Int64, nullable=True, required=False),
            "curation_level": pa.Column(pa.Int64, nullable=True, required=False),
        },
        coerce=True,
        strict=False,
    )


def targets_schema() -> pa.DataFrameSchema:
    return pa.DataFrameSchema(
        {
            "target_chembl_id": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "load_meta_id": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "hash_business_key": pa.Column(pa.String, nullable=False, checks=_HASH),
            "hash_row": pa.Column(pa.String, nullable=False, checks=_HASH),
            "pref_name": pa.Column(pa.String, nullable=True, required=False),
            "target_type": pa.Column(pa.String, nullable=True, required=False),
            "organism": pa.Column(pa.String, nullable=True, required=False),
            "tax_id": pa.Column(pa.Int64, nullable=True, required=False),
            "species_group_flag": pa.Column(pa.Int64, nullable=True, required=False),
            "cross_references__flat": pa.Column(pa.String, nullable=True, required=False),
            "target_components__flat": pa.Column(pa.String, nullable=True, required=False),
            "target_component_synonyms__flat": pa.Column(pa.String, nullable=True, required=False),
            "uniprot_accessions": pa.Column(pa.String, nullable=True, required=False),
            "protein_class_desc": pa.Column(pa.String, nullable=True, required=False),
            "protein_class_list": pa.Column(pa.String, nullable=True, required=False),
            "protein_class_top": pa.Column(pa.String, nullable=True, required=False),
            "component_count": pa.Column(pa.Int64, nullable=True, required=False),
        },
        coerce=True,
        strict=False,
    )


def documents_schema() -> pa.DataFrameSchema:
    return pa.DataFrameSchema(
        {
            "document_chembl_id": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "source": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "hash_business_key": pa.Column(pa.String, nullable=False, checks=_HASH),
            "hash_row": pa.Column(pa.String, nullable=False, checks=_HASH),
            "load_meta_id": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "doc_type": pa.Column(pa.String, nullable=True, required=False),
            "journal": pa.Column(pa.String, nullable=True, required=False),
            "journal_full_title": pa.Column(pa.String, nullable=True, required=False),
            "doi": pa.Column(pa.String, nullable=True, required=False),
            "doi_clean": pa.Column(pa.String, nullable=True, required=False),
            "pubmed_id": pa.Column(pa.String, nullable=True, required=False),
            "year": pa.Column(pa.Int64, nullable=True, required=False),
            "volume": pa.Column(pa.String, nullable=True, required=False),
            "issue": pa.Column(pa.String, nullable=True, required=False),
            "first_page": pa.Column(pa.String, nullable=True, required=False),
            "last_page": pa.Column(pa.String, nullable=True, required=False),
            "authors": pa.Column(pa.String, nullable=True, required=False),
            "authors_count": pa.Column(pa.Int64, nullable=True, required=False),
            "src_id": pa.Column(pa.Int64, nullable=True, required=False),
            "title": pa.Column(pa.String, nullable=True, required=False),
            "abstract": pa.Column(pa.String, nullable=True, required=False),
            "term": pa.Column(pa.String, nullable=True, required=False),
            "weight": pa.Column(pa.Float64, nullable=True, required=False),
        },
        coerce=True,
        strict=False,
    )


def testitems_schema() -> pa.DataFrameSchema:
    return pa.DataFrameSchema(
        {
            "molecule_chembl_id": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "_chembl_db_version": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "_api_version": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "load_meta_id": pa.Column(pa.String, nullable=False, checks=pa.Check.str_length(min_value=1)),
            "hash_business_key": pa.Column(pa.String, nullable=False, checks=_HASH),
            "hash_row": pa.Column(pa.String, nullable=False, checks=_HASH),
            "pref_name": pa.Column(pa.String, nullable=True, required=False),
            "molecule_type": pa.Column(pa.String, nullable=True, required=False),
            "max_phase": pa.Column(pa.Int64, nullable=True, required=False),
            "first_approval": pa.Column(pa.Int64, nullable=True, required=False),
            "first_in_class": pa.Column(pa.Int64, nullable=True, required=False),
            "availability_type": pa.Column(pa.Int64, nullable=True, required=False),
            "black_box_warning": pa.Column(pa.Int64, nullable=True, required=False),
            "chirality": pa.Column(pa.Int64, nullable=True, required=False),
            "dosed_ingredient": pa.Column(pa.Int64, nullable=True, required=False),
            "helm_notation": pa.Column(pa.String, nullable=True, required=False),
            "indication_class": pa.Column(pa.String, nullable=True, required=False),
            "inorganic_flag": pa.Column(pa.Int64, nullable=True, required=False),
            "natural_product": pa.Column(pa.Int64, nullable=True, required=False),
            "prodrug": pa.Column(pa.Int64, nullable=True, required=False),
            "structure_type": pa.Column(pa.String, nullable=True, required=False),
            "therapeutic_flag": pa.Column(pa.Int64, nullable=True, required=False),
            "molecule_hierarchy__molecule_chembl_id": pa.Column(pa.String, nullable=True, required=False),
            "molecule_hierarchy__parent_chembl_id": pa.Column(pa.String, nullable=True, required=False),
            "molecule_structures__canonical_smiles": pa.Column(pa.String, nullable=True, required=False),
            "molecule_structures__molfile": pa.Column(pa.String, nullable=True, required=False),
            "molecule_structures__standard_inchi": pa.Column(pa.String, nullable=True, required=False),
            "molecule_structures__standard_inchi_key": pa.Column(pa.String, nullable=True, required=False),
            "molecule_properties__alogp": pa.Column(pa.Float64, nullable=True, required=False),
            "molecule_properties__aromatic_rings": pa.Column(pa.Int64, nullable=True, required=False),
            "molecule_properties__cx_logd": pa.Column(pa.Float64, nullable=True, required=False),
            "molecule_properties__cx_logp": pa.Column(pa.Float64, nullable=True, required=False),
            "molecule_properties__cx_most_apka": pa.Column(pa.Float64, nullable=True, required=False),
            "molecule_properties__cx_most_bpka": pa.Column(pa.Float64, nullable=True, required=False),
            "molecule_properties__full_molformula": pa.Column(pa.String, nullable=True, required=False),
            "molecule_properties__full_mwt": pa.Column(pa.Float64, nullable=True, required=False),
            "molecule_properties__hba": pa.Column(pa.Int64, nullable=True, required=False),
            "molecule_properties__hba_lipinski": pa.Column(pa.Int64, nullable=True, required=False),
            "molecule_properties__hbd": pa.Column(pa.Int64, nullable=True, required=False),
            "molecule_properties__hbd_lipinski": pa.Column(pa.Int64, nullable=True, required=False),
            "molecule_properties__heavy_atoms": pa.Column(pa.Int64, nullable=True, required=False),
            "molecule_properties__molecular_species": pa.Column(pa.String, nullable=True, required=False),
            "molecule_properties__mw_freebase": pa.Column(pa.Float64, nullable=True, required=False),
            "molecule_properties__mw_monoisotopic": pa.Column(pa.Float64, nullable=True, required=False),
            "molecule_properties__num_lipinski_ro5_violations": pa.Column(pa.Int64, nullable=True, required=False),
            "molecule_properties__num_ro5_violations": pa.Column(pa.Int64, nullable=True, required=False),
            "molecule_properties__psa": pa.Column(pa.Float64, nullable=True, required=False),
            "molecule_properties__qed_weighted": pa.Column(pa.Float64, nullable=True, required=False),
            "molecule_properties__ro3_pass": pa.Column(pa.String, nullable=True, required=False),
            "molecule_properties__rtb": pa.Column(pa.Int64, nullable=True, required=False),
            "atc_classifications": pa.Column(pa.String, nullable=True, required=False),
            "cross_references__flat": pa.Column(pa.String, nullable=True, required=False),
            "molecule_synonyms__flat": pa.Column(pa.String, nullable=True, required=False),
        },
        coerce=True,
        strict=False,
    )


__all__ = [
    "activity_schema",
    "assays_schema",
    "targets_schema",
    "documents_schema",
    "testitems_schema",
]
