"""Базовые абстракции и исключения клиентского слоя."""

from bioetl.clients.base.exceptions import (  # noqa: F401
    ConfigurationError,
    ConnectionError,
    HTTPError,
    PaginationError,
    ProviderError,
    RequestException,
    Timeout,
)
from bioetl.clients.base.interfaces import (  # noqa: F401
    FACTORIES,
    ClientFactory,
    ClientProtocol,
    DataProviderProtocol,
    Page,
    PageStream,
    PaginationParams,
    RecordStream,
    RequestContext,
    RetryOptions,
    SupportsBatch,
    SupportsSearch,
    TransportOptions,
    get_factory,
    register_domain_factories,
    register_factory,
)

__all__ = [
    "ConfigurationError",
    "ConnectionError",
    "HTTPError",
    "PaginationError",
    "ProviderError",
    "RequestException",
    "Timeout",
    "FACTORIES",
    "ClientFactory",
    "ClientProtocol",
    "DataProviderProtocol",
    "SupportsBatch",
    "SupportsSearch",
    "PaginationParams",
    "RequestContext",
    "RecordStream",
    "Page",
    "PageStream",
    "TransportOptions",
    "RetryOptions",
    "register_factory",
    "register_domain_factories",
    "get_factory",
]
