sources:
  chembl:
    enabled: true
    base_url: "https://www.ebi.ac.uk/chembl/api/data"
    batch_size: 20
    max_url_length: 2000
    headers:
      Accept: "application/json"
      User-Agent: "bioetl-chembl-default/1.0"
    http:
      rate_limit_jitter: true
