sources:
  iuphar:
    enabled: true
    base_url: "https://www.guidetopharmacology.org/services"
    http_profile: iuphar
    stage: enrichment
    api_key: "${IUPHAR_API_KEY}"
    headers:
      x-api-key: "${IUPHAR_API_KEY}"
    rate_limit:
      max_calls: 6
      period: 1.0
    cache_enabled: true
    cache_ttl: 14400
