sources:
  openalex:
    enabled: true
    base_url: "https://api.openalex.org"
    mailto: "${OPENALEX_MAILTO}"
    headers:
      User-Agent: "bioetl-openalex-client/1.0"
    batch_size: 100
    rate_limit_max_calls: 10
    rate_limit_period: 1.0
    workers: 4
