sources:
  pubmed:
    enabled: true
    base_url: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
    tool: "${PUBMED_TOOL}"
    email: "${PUBMED_EMAIL}"
    # api_key: "${PUBMED_API_KEY:}"
    batch_size: 200
    rate_limit_max_calls: 3
    rate_limit_period: 1.0
    workers: 1
