sources:
  uniprot:
    enabled: true
    base_url: "https://rest.uniprot.org/uniprotkb"
    http_profile: uniprot
    stage: enrichment
    rate_limit:
      max_calls: 3
      period: 1.0
    cache_enabled: true
    cache_ttl: 21600
