sources:
  uniprot_idmapping:
    enabled: true
    base_url: "https://rest.uniprot.org/idmapping"
    http_profile: uniprot_idmapping
    stage: enrichment
    rate_limit:
      max_calls: 2
      period: 1.0
    cache_enabled: true
    cache_ttl: 21600
