version: 1
pipeline:
  name: "base"
  entity: "abstract"
  release_scope: true

http:
  global:
    timeout_sec: 60.0
    retries:
      total: 5
      backoff_multiplier: 2.0
      backoff_max: 120.0
      statuses: [408, 425, 429, 500, 502, 503, 504]
    rate_limit:
      max_calls: 5
      period: 15.0
    headers: {}

cache:
  enabled: true
  directory: "data/cache"
  ttl: 86400
  release_scoped: true

paths:
  input_root: "data/input"
  output_root: "data/output"

materialization:
  defaults:
    root: "{entity}"
  stages:
    bronze:
      format: parquet
      filename: "{dataset}_bronze.parquet"
      description: "Raw materialized extracts"
    silver:
      format: parquet
      filename: "{dataset}_silver.parquet"
      description: "Normalized intermediate dataset"
    gold:
      format: parquet
      filename: "{dataset}_final.parquet"
      description: "Curated analytics-ready dataset"
    qc_report:
      format: csv
      filename: "{dataset}_qc.csv"
      description: "Quality control summary report"

determinism:
  sort:
    by: []
    ascending: []
  column_order: []

sources:
  pubchem:
    enabled: true
    base_url: "https://pubchem.ncbi.nlm.nih.gov/rest/pug"
    headers:
      Accept: "application/json"
      User-Agent: "bioetl-pubchem-default/1.0"

postprocess:
  qc:
    enabled: true

qc:
  enabled: true
  severity_threshold: "warning"
  thresholds: {}

cli:
  default_config: "configs/base.yaml"

