version: 1
pipeline:
  name: "base"
  entity: "abstract"
  release_scope: true

http:
  global:
    timeout_sec: 60.0
    retries:
      total: 5
      backoff_multiplier: 2.0
      backoff_max: 120.0
      statuses: [404, 408, 409, 425, 429, 500, 502, 503, 504]
    rate_limit:
      max_calls: 5
      period: 15.0
    headers: {}

cache:
  enabled: true
  directory: "data/cache"
  ttl: 86400
  release_scoped: true

paths:
  input_root: "data/input"
  output_root: "data/output"

determinism:
  sort:
    by: []
    ascending: []
  column_order: []

postprocess:
  qc:
    enabled: true

qc:
  enabled: true
  severity_threshold: "warning"
  thresholds: {}
  schema_thresholds: {}

cli:
  default_config: "configs/base.yaml"

