# Конфигурация для полной обработки документов со всеми источниками
# Включает все доступные API и максимальную детализацию

# Глобальные настройки HTTP-клиента
http:
  global:
    # Максимальное время ожидания ответа от сервера в секундах
    timeout_sec: 60.0  # Увеличенный таймаут для всех запросов
    # Настройки повторных попыток при неудачных запросах
    retries:
      # Общее количество попыток (включая первую)
      total: 10
      # Множитель для экспоненциальной задержки между попытками
      backoff_multiplier: 3.0
      # Настройки ограничения скорости запросов по умолчанию
      rate_limit:
        max_calls: 3
        period: 1.0      
      # Заголовки, отправляемые с каждым HTTP-запросом
      headers:
      # Идентификатор клиента для API-провайдеров
        Accept: application/json
        User-Agent: bioactivity-data-acquisition/0.1.0

# Конфигурация источников данных
sources:
  # ChEMBL - база данных химических соединений и биологической активности
  chembl:
    # Уникальное имя источника
    name: chembl
    # API endpoint для получения документов
    endpoint: document
    # Параметры запроса к API
    params:
      # Тип документов для поиска (статьи)
      document_type: article
    # Переопределения настроек пагинации
    pagination:
      # Количество записей на странице (больше для ChEMBL)
      size: 200
      # Максимальное количество страниц для обработки
      max_pages: 50  # Больше страниц для полной обработки
    # Переопределения HTTP настроек
    http:
      # Базовый URL API ChEMBL
      base_url: https://www.ebi.ac.uk/chembl/api/data
      # Таймаут для запросов к ChEMBL (больше из-за сложности данных)
      timeout_sec: 120.0  # Увеличенный таймаут для ChEMBL
      # Дополнительные заголовки для ChEMBL
      headers:
        # Токен авторизации (заменяется на реальный токен)
        Authorization: "Bearer {chembl_api_token}"

  # Crossref - сервис для получения метаданных научных публикаций
  crossref:
    # Уникальное имя источника
    name: crossref
    # Параметры поиска в Crossref
    params:
      # Поисковый запрос (ищем публикации связанные с ChEMBL)
      query: chembl
      # Поля, которые нужно получить из API
      select: DOI,title
    # Переопределения настроек пагинации
    pagination:
      # Параметр курсора для навигации по страницам
      page_param: cursor
      # Параметр количества записей на странице
      size_param: rows
      # Максимальное количество страниц
      max_pages: 20  # Больше страниц для полной обработки
    # Переопределения HTTP настроек
    http:
      # Базовый URL API Crossref
      base_url: https://api.crossref.org/works
      # Дополнительные заголовки для Crossref
      headers:
        # API ключ для Crossref Plus (заменяется на реальный ключ)
        Crossref-Plus-API-Token: "{crossref_api_key}"

  # OpenAlex - открытая база данных научных публикаций
  openalex:
    # Уникальное имя источника
    name: openalex
    # Переопределения HTTP настроек
    http:
      # Базовый URL API OpenAlex
      base_url: https://api.openalex.org/works
      # Переопределения настроек повторных попыток
      retries:
        # Общее количество попыток
        total: 20
        # Множитель задержки между попытками
        backoff_multiplier: 5.0

  # PubMed - база данных биомедицинской литературы NCBI
  pubmed:
    # Уникальное имя источника
    name: pubmed
    # Включен ли источник
    enabled: true
    # Настройки ограничения скорости запросов (rate limiting)
    rate_limit:
      # Максимальное количество запросов в период
      max_calls: 5  # Увеличенный лимит при наличии API ключа
      # Период в секундах для подсчета запросов
      period: 1.0
    # HTTP настройки для PubMed
    http:
      # Базовый URL для E-utilities API NCBI
      base_url: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/
      # Таймаут для запросов (больше из-за сложности PubMed)
      timeout_sec: 120.0
      # Заголовки для запросов
      headers:
        # Предпочитаемый формат ответа
        Accept: application/json
        # Идентификатор клиента
        User-Agent: bioactivity-data-acquisition/0.1.0
        # API ключ для PubMed (заменяется на реальный ключ)
        api_key: "{PUBMED_API_KEY}"
      # Настройки повторных попыток для PubMed
      retries:
        # Общее количество попыток
        total: 15
        # Множитель задержки между попытками
        backoff_multiplier: 4.0

  # Semantic Scholar - AI-платформа для научных публикаций
  semantic_scholar:
    # Уникальное имя источника
    name: semantic_scholar
    # Включен ли источник
    enabled: true  # Включен для полной обработки
    # Настройки ограничения скорости запросов
    rate_limit:
      # Максимальное количество запросов в период
      max_calls: 2  # Увеличенный лимит при наличии API ключа
      # Период в секундах (1 минута)
      period: 60.0  # 1 минута
    # HTTP настройки для Semantic Scholar
    http:
      # Базовый URL API Semantic Scholar
      base_url: https://api.semanticscholar.org/graph/v1/paper
      # Таймаут для запросов
      timeout_sec: 120.0
      # Заголовки для запросов
      headers:
        # Предпочитаемый формат ответа
        Accept: application/json
        # Идентификатор клиента
        User-Agent: bioactivity-data-acquisition/0.1.0        
        # API ключ для Semantic Scholar (заменяется на реальный ключ        
        x-api-key: "{SEMANTIC_SCHOLAR_API_KEY}"
      # Настройки повторных попыток
      retries:
        # Общее количество попыток
        total: 20
        # Множитель задержки между попытками
        backoff_multiplier: 5.0

# Настройки ввода-вывода данных
io:
  # Настройки входных данных
  input:
    # Путь к CSV файлу с исходными документами
    documents_csv: data/input/documents.csv
  # Настройки выходных данных
  output:
    # Директория для сохранения результатов
    dir: data/output/full
    # Формат выходных файлов
    format: csv
    # Специфичные настройки для CSV формата
    csv:
      # Кодировка файла
      encoding: utf-8
      # Формат чисел с плавающей точкой (3 знака после запятой)
      float_format: "%.3f"
      # Формат даты и времени (ISO 8601)
      date_format: "%Y-%m-%dT%H:%M:%SZ"

# Настройки выполнения программы
runtime:
  # Количество параллельных воркеров для обработки данных
  workers: 8  # Больше воркеров для полной обработки
  # Ограничение на количество обрабатываемых записей (null = без ограничений)
  limit: null  # Без ограничений
  # Режим тестирования (true = только симуляция, false = реальная обработка)
  dry_run: false
  # Тег даты для именования файлов (null = автоматическая генерация)
  date_tag: null  # Автоматически генерируется

# Настройки логирования
logging:
  # Уровень детализации логов (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: WARNING

# Настройки валидации данных
validation:
  # Строгий режим валидации (true = останавливать при ошибках)
  strict: true
  # Настройки контроля качества (QC)
  qc:
    # Максимальная доля пропущенных значений (2%)
    max_missing_fraction: 0.02  # Более строгие требования
    # Максимальная доля дублирующихся записей (0.5%)
    max_duplicate_fraction: 0.005

# Настройки детерминизма для воспроизводимости результатов
determinism:
  # Настройки сортировки данных
  sort:
    # Поля для сортировки (в порядке приоритета)
    by:
      - document_chembl_id  # ID документа в ChEMBL
      - title               # Название публикации
      - doi                 # DOI публикации
    # Направление сортировки для каждого поля
    ascending:
      - true   # document_chembl_id - по возрастанию
      - true   # title - по возрастанию
      - true   # doi - по возрастанию
    # Позиция для значений NULL/NA (last = в конце)
    na_position: last
  # Порядок колонок в выходном файле
  column_order:
    # Основные поля документа (оригинальные из ChEMBL)
    - document_chembl_id      # ID документа в ChEMBL
    - title                   # Название публикации (объединенное)
    - doi                     # DOI публикации (объединенный)
    - pubmed_id               # PubMed идентификатор
    - journal                 # Название журнала (нормализованное)
    - year                    # Год публикации
    - abstract                # Аннотация документа
    - authors                 # Авторы документа
    - classification          # Классификация документа
    - document_contains_external_links  # Содержит ли документ внешние ссылки
    - first_page              # Номер первой страницы
    - is_experimental_doc     # Является ли документ экспериментальным
    - issue                   # Номер выпуска журнала
    - last_page               # Номер последней страницы
    - month                   # Месяц публикации
    - volume                  # Том журнала
    - citation                # Форматированная литературная ссылка
    - retrieved_at            # Время получения данных
    
    # Поля из ChEMBL
    - chembl_title            # Название из ChEMBL
    - chembl_pubmed_id        # PMID из ChEMBL
    - chembl_journal          # Название журнала из ChEMBL
    - chembl_year             # Год из ChEMBL
    - chembl_volume           # Том из ChEMBL
    - chembl_issue            # Номер выпуска из ChEMBL
    
    # Поля из Crossref
    - crossref_title          # Название из Crossref
    - crossref_subject        # Предметная область из Crossref
    - crossref_journal        # Название журнала из Crossref
    - crossref_volume         # Том из Crossref
    - crossref_issue          # Номер выпуска из Crossref
    - crossref_first_page     # Первая страница из Crossref
    - crossref_last_page      # Последняя страница из Crossref
    - crossref_year           # Год из Crossref
    - crossref_error          # Ошибка из Crossref
    
    # Поля из OpenAlex
    - openalex_title          # Название из OpenAlex
    - openalex_doc_type       # Тип документа из OpenAlex
    - openalex_publication_year  # Год публикации из OpenAlex
    - openalex_journal        # Название журнала из OpenAlex
    - openalex_volume         # Том из OpenAlex
    - openalex_issue          # Номер выпуска из OpenAlex
    - openalex_first_page     # Первая страница из OpenAlex
    - openalex_last_page      # Последняя страница из OpenAlex
    - openalex_year           # Год из OpenAlex
    - openalex_error          # Ошибка из OpenAlex
    
    # Поля из PubMed (расширенные)
    - pubmed_pmid             # PMID из PubMed
    - pubmed_article_title    # Название статьи из PubMed
    - pubmed_abstract         # Полный текст аннотации из PubMed
    - pubmed_journal_title    # Название журнала из PubMed
    - pubmed_volume           # Том журнала из PubMed
    - pubmed_issue            # Номер выпуска из PubMed
    - pubmed_start_page       # Начальная страница из PubMed
    - pubmed_end_page         # Конечная страница из PubMed
    - pubmed_publication_type # Тип публикации из PubMed
    - pubmed_mesh_descriptors # MeSH дескрипторы из PubMed
    - pubmed_mesh_qualifiers  # MeSH квалификаторы из PubMed
    - pubmed_chemical_list    # Список химических веществ из PubMed
    - pubmed_year_completed   # Год завершения из PubMed
    - pubmed_month_completed  # Месяц завершения из PubMed
    - pubmed_day_completed    # День завершения из PubMed
    - pubmed_year_revised     # Год пересмотра из PubMed
    - pubmed_month_revised    # Месяц пересмотра из PubMed
    - pubmed_day_revised      # День пересмотра из PubMed
    - pubmed_issn             # ISSN журнала из PubMed
    - pubmed_authors          # Авторы из PubMed
    - pubmed_year             # Год из PubMed
    - pubmed_error            # Ошибка из PubMed
    
    # Поля из Semantic Scholar
    - semantic_scholar_pmid   # PMID из Semantic Scholar
    - semantic_scholar_semantic_scholar_id  # ID из Semantic Scholar
    - semantic_scholar_venue  # Название журнала из Semantic Scholar
    - semantic_scholar_external_ids         # Внешние ID из Semantic Scholar
    - semantic_scholar_error  # Ошибка из Semantic Scholar
    
    # Группа полей DOI из всех источников
    - chembl_doi              # DOI из ChEMBL
    - openalex_doi_key        # DOI из OpenAlex
    - pubmed_doi              # DOI из PubMed
    - semantic_scholar_doi    # DOI из Semantic Scholar
    
    # Группа полей типов публикации из всех источников
    - doc_type                # Тип документа из ChEMBL
    - crossref_doc_type       # Тип документа из Crossref
    - openalex_type_crossref  # Тип документа из OpenAlex
    - pubmed_publication_type # Тип публикации из PubMed
    - semantic_scholar_publication_types    # Типы публикации из Semantic Scholar

# Настройки постобработки данных
postprocess:
  # Контроль качества данных
  qc:
    # Включить анализ качества данных
    enabled: true
  # Корреляционный анализ между источниками
  correlation:
    # Включить анализ корреляций
    enabled: true
  # Нормализация названий журналов
  journal_normalization:
    # Включить нормализацию журналов
    enabled: true
    # Колонки для нормализации названий журналов
    columns: [
      "journal",                # Основная колонка журнала
      "pubmed_journal_title",   # Название журнала из PubMed
      "chembl_journal",         # Название журнала из ChEMBL
      "crossref_journal",       # Название журнала из Crossref
      "openalex_journal",       # Название журнала из OpenAlex
      "semantic_scholar_venue"  # Название журнала из Semantic Scholar
    ]
  # Форматирование цитат
  citation_formatting:
    # Включить форматирование цитат
    enabled: true
    # Маппинг колонок для форматирования цитат
    columns:
      journal: "journal"        # Колонка с названием журнала
      volume: "volume"          # Колонка с томом
      issue: "issue"            # Колонка с номером выпуска
      first_page: "first_page"  # Колонка с первой страницей
      last_page: "last_page"    # Колонка с последней страницей
