# Унифицированный шаблон конфигурации для всех ETL пайплайнов
# Этот шаблон обеспечивает единообразную структуру для всех пайплайнов

# Метаданные пайплайна
pipeline:
  name: "<entity_name>"  # documents, targets, assays, activities, testitems
  version: "1.0.0"
  entity_type: "<entity_type>"  # documents|targets|assays|activities|testitems
  description: "ETL pipeline for <entity_name> data"

# HTTP настройки
http:
  global:
    timeout_sec: 60.0
    retries:
      total: 5
      backoff_multiplier: 2.0
      backoff_max: 120.0
    rate_limit:
      max_calls: 5
      period: 15.0
    headers:
      Accept: "application/json"
      User-Agent: "bioactivity-data-acquisition/0.1.0"
    verify_ssl: true
    follow_redirects: true

# Источники данных
sources:
  chembl:
    enabled: true
    http:
      base_url: "https://www.ebi.ac.uk/chembl/api/data"
      timeout_sec: 60.0
      retries:
        total: 3
        backoff_multiplier: 1.5
    # Специфичные параметры для ChEMBL
    batch_size: 1000
    max_compounds: null
    
  uniprot:
    enabled: false
    http:
      base_url: "https://rest.uniprot.org"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    # Специфичные параметры для UniProt
    batch_size: 100
    
  iuphar:
    enabled: false
    http:
      base_url: "https://www.guidetopharmacology.org"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    # Специфичные параметры для IUPHAR
    
  pubchem:
    enabled: false
    http:
      base_url: "https://pubchem.ncbi.nlm.nih.gov/rest/pug"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    # Специфичные параметры для PubChem
    
  crossref:
    enabled: false
    http:
      base_url: "https://api.crossref.org"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    # Специфичные параметры для Crossref
    
  openalex:
    enabled: false
    http:
      base_url: "https://api.openalex.org"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    # Специфичные параметры для OpenAlex
    
  pubmed:
    enabled: false
    http:
      base_url: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    # Специфичные параметры для PubMed
    
  semanticscholar:
    enabled: false
    http:
      base_url: "https://api.semanticscholar.org"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    # Специфичные параметры для Semantic Scholar

# Ввод-вывод
io:
  input:
    path: "data/input/<entity>.csv"
    encoding: "utf-8"
    # Специфичные параметры ввода для каждого пайплайна
    
  output:
    dir: "data/output/<entity>"
    format: "csv"
    csv:
      encoding: "utf-8"
      float_format: "%.6f"
      date_format: "%Y-%m-%dT%H:%M:%SZ"
      na_rep: ""
      line_terminator: "\n"
    # Специфичные параметры вывода

# Runtime настройки
runtime:
  workers: 4
  limit: null  # null означает без ограничений
  offset: 0
  dry_run: false
  date_tag: null  # null означает автоматическую генерацию
  dev_mode: false
  allow_incomplete_sources: false

# Логирование
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file:
    enabled: true
    path: "data/logs/<entity>.log"
    max_size: "10MB"
    backup_count: 5
  console:
    enabled: true
    format: "text"  # text|json
  structured: true

# Детерминизм
determinism:
  sort:
    by: ["<primary_key>"]  # Список колонок для сортировки
    ascending: [true]  # Соответствующий порядок сортировки
    na_position: "last"  # first|last
  column_order:
    - "<primary_key>"
    # ... остальные колонки в желаемом порядке
  # Дополнительные настройки детерминизма

# Валидация
validation:
  enabled: true
  strict: false
  schema_validation: true
  data_quality_checks: true
  # Специфичные настройки валидации

# Постобработка
postprocess:
  qc:
    enabled: true
    fail_on: []  # Список метрик, при которых пайплайн должен завершиться с ошибкой
    thresholds: {}  # Пороги для метрик качества
    detailed_report: false  # Генерировать ли детальный QC отчет
    
  correlation:
    enabled: false  # Включить корреляционный анализ
    methods: ["pearson", "spearman"]  # Методы корреляционного анализа
    min_correlation: 0.5  # Минимальная корреляция для включения в отчет
    
  # Специфичные шаги постобработки для каждого пайплайна
  steps: []
  
# Нормализация
normalization:
  enabled: true
  # Специфичные настройки нормализации для каждого пайплайна
  
# Качество данных
quality:
  profiles:
    # Профили качества для разных типов данных
    default:
      enabled: true
      rules: []
  
# Кэширование
cache:
  enabled: true
  dir: "data/cache/<entity>"
  ttl: 86400  # Время жизни кэша в секундах (24 часа)
  max_size: "1GB"
  
# Мониторинг и телеметрия
telemetry:
  enabled: false
  endpoint: null
  api_key: null
  batch_size: 100
  flush_interval: 30.0
