# Конфигурация с включенной расширенной QC отчетностью
# Производная от базовой конфигурации с дополнительными настройками качества

# Настройки логирования
logging:
  level: INFO
  format: json

# Настройки выполнения
runtime:
  workers: 4
  timeout: 300

# Настройки источников данных
sources:
  chembl:
    base_url: "https://www.ebi.ac.uk/chembl/api/data"
    pagination:
      max_pages: 10
      per_page: 1000
    retry:
      total: 3
      backoff_multiplier: 2.0
    rate_limit:
      requests_per_second: 10
      burst_size: 20

# Настройки трансформации данных
transforms:
  normalization:
    trim_strings: true
    standardize_case: false
  validation:
    strict: false
    coerce_types: true

# Настройки детерминизма
determinism:
  column_order:
    - compound_id
    - target_id
    - activity_value
    - standard_value
    - publication_date
    - doi
    - pmid
  sort:
    by: ["compound_id", "target_id"]
    ascending: true
    na_position: "last"

# Настройки постобработки с расширенной QC
postprocess:
  qc:
    enabled: true
    enhanced: true  # Включаем расширенную QC отчетность
  correlation:
    enabled: true
    enhanced: true  # Включаем расширенный корреляционный анализ

# Настройки валидации QC
validation:
  strict: false
  qc:
    max_missing_fraction: 0.1  # Максимум 10% пропущенных значений
    max_duplicate_fraction: 0.05  # Максимум 5% дублированных записей

# Настройки HTTP
http:
  global:
    timeout: 30
    verify_ssl: true
  session:
    pool_connections: 10
    pool_maxsize: 20

# Настройки вывода
io:
  output:
    format: csv
    data_path: "data/output/bioactivity_enhanced_qc.csv"
    qc_report_path: "data/output/bioactivity_enhanced_qc_quality_report.csv"
    correlation_path: "data/output/bioactivity_enhanced_qc_correlation.csv"
    csv:
      encoding: "utf-8"
      float_format: "%.6f"
      date_format: "%Y-%m-%d"
      na_rep: ""
    parquet:
      compression: "snappy"

# Клиенты для извлечения данных
clients:
  - name: "chembl"
    type: "bioactivity"
    source: "chembl"
    filters:
      activity_relation: ["=", ">=", "<=", ">", "<"]
      standard_type: ["IC50", "EC50", "Ki", "Kd"]
    limit: 1000
