# Конфигурация для пайплайна извлечения и нормализации сущности assay из ChEMBL
# Следует стандартам проекта и архитектуре ETL

# Глобальные настройки HTTP-клиента
http:
  global:
    # Максимальное время ожидания ответа от сервера в секундах
    timeout_sec: 60.0
    # Настройки повторных попыток при неудачных запросах
    retries:
      # Общее количество попыток (включая первую)
      total: 10
      # Множитель для экспоненциальной задержки между попытками
      backoff_multiplier: 3.0
    # Настройки ограничения скорости запросов по умолчанию
    # Оптимизировано для ChEMBL API - увеличен лимит запросов
    rate_limit:
      max_calls: 10
      period: 15.0
    # Заголовки, отправляемые с каждым HTTP-запросом
    headers:
      Accept: application/json
      User-Agent: bioactivity-data-acquisition/0.1.0

# Конфигурация источников данных
sources:
  # ChEMBL - база данных химических соединений и биологической активности
  chembl:
    # Уникальное имя источника
    name: chembl
    # API endpoint для получения ассев
    endpoint: assay
    # Параметры запроса к API
    params:
      # Формат ответа
      format: json
      # Количество записей на странице (увеличено для оптимизации)
      limit: 1000
    # Переопределения настроек пагинации
    pagination:
      # Параметр смещения для пагинации
      offset_param: offset
      # Параметр количества записей на странице
      size_param: limit
      # Количество записей на странице (увеличено для оптимизации)
      size: 1000
      # Максимальное количество страниц для обработки
      max_pages: 50
    # Переопределения HTTP настроек
    http:
      # Базовый URL API ChEMBL
      base_url: https://www.ebi.ac.uk/chembl/api/data
      # Таймаут для запросов к ChEMBL (оптимизирован)
      timeout_sec: 60.0
      # Дополнительные заголовки для ChEMBL
      headers:
        # Токен авторизации (заменяется на реальный токен)
        Authorization: "Bearer {chembl_api_token}"
      # Настройки повторных попыток для ChEMBL (оптимизированы)
      retries:
        # Общее количество попыток
        total: 5
        # Множитель задержки между попытками
        backoff_multiplier: 2.0

# Настройки ввода-вывода данных
io:
  # Настройки входных данных
  input:
    # Путь к CSV файлу с идентификаторами ассев
    assay_ids_csv: data/input/assay_ids.csv
    # Путь к CSV файлу с идентификаторами таргетов (альтернативный вход)
    target_ids_csv: data/input/target_ids.csv
    # Название колонки в CSV для чтения ID ассев (по умолчанию: assay_chembl_id)
    assay_id_column: assay_chembl_id
  # Настройки выходных данных
  output:
    # Директория для сохранения результатов
    dir: data/output/assay
    # Формат выходных файлов
    format: csv
    # Специфичные настройки для CSV формата
    csv:
      # Кодировка файла
      encoding: utf-8
      # Формат чисел с плавающей точкой (3 знака после запятой)
      float_format: "%.3f"
      # Формат даты и времени (ISO 8601)
      date_format: "%Y-%m-%dT%H:%M:%SZ"
      # Представление отсутствующих значений
      na_rep: ""
    # Специфичные настройки для Parquet формата
    parquet:
      # Сжатие данных
      compression: snappy

# Настройки выполнения программы
runtime:
  # Количество параллельных воркеров для обработки данных (увеличено для оптимизации)
  workers: 16
  # Ограничение на количество обрабатываемых записей (null = без ограничений)
  limit: null
  # Режим тестирования (true = только симуляция, false = реальная обработка)
  dry_run: false
  # Тег даты для именования файлов (автоматическая генерация)
  # date_tag будет сгенерирован автоматически

# Настройки логирования
logging:
  # Уровень детализации логов (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: INFO
  # Настройки файлового логирования
  file:
    enabled: true
    path: data/logs/assay.log
    max_bytes: 10485760  # 10MB
    backup_count: 10
    rotation_strategy: size
    retention_days: 14

# Настройки валидации данных
validation:
  # Строгий режим валидации (true = останавливать при ошибках)
  strict: true
  # Настройки контроля качества (QC)
  qc:
    # Максимальная доля пропущенных значений (2%)
    max_missing_fraction: 0.02
    # Максимальная доля дублирующихся записей (0.5%)
    max_duplicate_fraction: 0.005

# Настройки детерминизма для воспроизводимости результатов
determinism:
  # Настройки сортировки данных
  sort:
    # Поля для сортировки (в порядке приоритета)
    by:
      - assay_chembl_id  # ID ассая в ChEMBL
    # Направление сортировки для каждого поля
    ascending:
      - true   # assay_chembl_id - по возрастанию
    # Позиция для значений NULL/NA (last = в конце)
    na_position: last
  # Порядок колонок в выходном файле
  column_order:
    # Основные поля ассая (ключи и идентификаторы)
    - assay_chembl_id         # ID ассая в ChEMBL
    - src_id                  # ID источника
    - src_name                # Название источника
    - src_assay_id            # ID ассая в источнике
    # Классификация ассая
    - assay_type              # Тип ассая (B/F/P/U)
    - assay_type_description  # Описание типа ассая
    - bao_format              # BAO формат
    - bao_label               # BAO метка
    - assay_category          # Категория ассая
    - assay_classifications   # Классификации ассая
    # Связь с таргетом
    - target_chembl_id        # ID таргета в ChEMBL
    - relationship_type       # Тип связи с таргетом
    - confidence_score        # Уровень уверенности
    # Вариантные данные
    - variant_id              # ID варианта
    - is_variant              # Флаг наличия вариантных данных
    - variant_accession       # Accession варианта
    - variant_sequence_accession  # Accession последовательности варианта
    - variant_sequence_mutation   # Мутация в последовательности варианта
    - variant_mutations       # Описание мутаций варианта
    - variant_sequence        # Последовательность варианта
    - variant_text            # Текстовое описание варианта
    - variant_sequence_id     # ID последовательности варианта
    - variant_organism        # Организм варианта
    # Таргет и изоформы
    - target_uniprot_accession # UniProt accession таргета
    - target_isoform          # Изоформа таргета
    # Биологический контекст
    - assay_organism          # Организм ассая
    - assay_tax_id            # Таксономический ID организма
    - assay_cell_type         # Тип клетки
    - assay_tissue            # Ткань
    - assay_strain            # Штамм
    - assay_subcellular_fraction  # Субклеточная фракция
    # Описание и протокол
    - description             # Описание ассая
    - assay_parameters        # Параметры ассая (legacy)
    - assay_parameters_json   # Параметры ассая (нормализованный JSON)
    - assay_format            # Формат ассая
    # Техслужебные поля
    - source_system           # Система-источник
    - chembl_release          # Версия ChEMBL
    - extracted_at            # Время извлечения
    - hash_row                # Хеш строки
    - hash_business_key       # Хеш бизнес-ключа

# Настройки постобработки данных
postprocess:
  # Контроль качества данных
  qc:
    # Включить анализ качества данных
    enabled: true
    # Расширенный QC анализ
    enhanced: true
  # Корреляционный анализ между источниками
  correlation:
    # Включить анализ корреляций
    enabled: true
    # Расширенный корреляционный анализ
    enhanced: true

# Профили фильтрации для различных сценариев использования
filter_profiles:
  # Профиль для человеческих белков с высокой уверенностью
  human_single_protein:
    target_organism: "Homo sapiens"
    target_type: "SINGLE PROTEIN"
    relationship_type: "D"
    confidence_score__range: "7,9"
    assay_type__in: "B,F"
  
  # Профиль для binding ассев
  binding_assays:
    assay_type: "B"
    relationship_type: "D"
    confidence_score__range: "5,9"
  
  # Профиль для функциональных ассев
  functional_assays:
    assay_type: "F"
    relationship_type: "D"
    confidence_score__range: "5,9"
  
  # Профиль для вариантных анализов
  variant_assays:
    target_organism: "Homo sapiens"
    target_type: "SINGLE PROTEIN"
    relationship_type__in: "D,H"  # Включаем оба типа отношений
    confidence_score__range: "7,9"
    assay_type__in: "B,F"
  
  # Профиль для высококачественных ассев
  high_quality:
    confidence_score__range: "7,9"
    relationship_type: "D"
    assay_type__in: "B,F"

# Настройки кэширования
cache:
  # Включить HTTP-кэш
  enabled: true
  # Директория для кэша
  directory: .cache/chembl
  # Время жизни кэша в секундах (увеличено для оптимизации - 24 часа)
  ttl: 86400
  # Инвалидировать кэш при смене релиза ChEMBL
  invalidate_on_release_change: true

# Настройки для работы с вариантами белков
variants:
  filters:
    include_wildtype: true  # Включать ли wildtype (не-варианты)
  fetch:
    batch_size: 200  # Размер батча для получения вариантных анализов
  # Настройки для производных колонок интерфейса/сервисов
  interface:
    # Включить извлечение variant_sequence_accession
    extract_sequence_accession: true
    # Включить извлечение variant_sequence_mutation  
    extract_sequence_mutation: true
    # Настройки для обработки мутаций
    mutation:
      # Формат для представления мутаций (compact/extended)
      format: "compact"
      # Включать ли информацию о позиции мутации
      include_position: true

# Настройки для работы с изоформами таргетов
targets:
  join_isoforms:
    enabled: true
    batch_size: 50

# =============================================================================
# ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ ДЛЯ API КЛЮЧЕЙ
# =============================================================================
# 
# Для использования API ключей установите следующие переменные окружения:
#
# Windows (PowerShell):
#   $env:CHEMBL_API_TOKEN = "your_chembl_token_here"
#
# Linux/macOS (bash):
#   export CHEMBL_API_TOKEN="your_chembl_token_here"
#
# ВАЖНО:
# - Система работает БЕЗ API ключей с ограничениями по rate limiting
# - При отсутствии API ключей используется graceful degradation
# - ChEMBL API работает без токена, но с ограничениями по запросам
#
# Получить API ключи можно по следующим ссылкам:
# - ChEMBL: https://chembl.gitbook.io/chembl-interface-documentation/web-services/chembl-data-web-services
