sources:
  - name: chembl
    base_url: "https://example.com"
    activities_endpoint: "/activities"
    page_size: 2
io:
  output:
    data_path: "data/output/bioactivities.csv"
    qc_report_path: "data/output/qc_report.csv"
    correlation_path: "data/output/correlation.csv"
    format: csv
    csv:
      encoding: "utf-8"
      float_format: "%.3f"
      date_format: "%Y-%m-%dT%H:%M:%SZ"
determinism:
  sort:
    by: ["compound_id", "target"]
    ascending: [true, true]
    na_position: last
  column_order:
    - compound_id
    - target
    - activity_value
    - activity_unit
    - source
    - retrieved_at
    - smiles
transforms:
  unit_conversion:
    nM: 1.0
    uM: 1000.0
    pM: 0.001
validation:
  strict: true
  qc:
    max_missing_fraction: 0.05
    max_duplicate_fraction: 0.01
postprocess:
  qc:
    enabled: true
  correlation:
    enabled: true
retries:
  max_tries: 3
logging:
  level: INFO
