# Конфигурация v2 для targets pipeline
# Основана на унифицированном шаблоне config.template.yaml

# Метаданные пайплайна
pipeline:
  name: "targets"
  version: "2.0.0"
  entity_type: "targets"
  description: "ETL pipeline for target data from ChEMBL, UniProt, and IUPHAR"

# HTTP настройки
http:
  global:
    timeout_sec: 60.0
    retries:
      total: 5
      backoff_multiplier: 2.0
      backoff_max: 120.0
    rate_limit:
      max_calls: 5
      period: 15.0
    headers:
      Accept: "application/json"
      User-Agent: "bioactivity-data-acquisition/0.1.0"
    verify_ssl: true
    follow_redirects: true

# Источники данных
sources:
  chembl:
    enabled: true
    http:
      base_url: "https://www.ebi.ac.uk/chembl/api/data"
      timeout_sec: 60.0
      retries:
        total: 3
        backoff_multiplier: 1.5
    batch_size: 1000
    max_compounds: null
    
  uniprot:
    enabled: true
    http:
      base_url: "https://rest.uniprot.org"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    batch_size: 100
    mapping_enabled: true
    
  iuphar:
    enabled: true
    http:
      base_url: "https://www.guidetopharmacology.org"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    batch_size: 50
    dictionary_path: "configs/dictionary/_target/_IUPHAR/_IUPHAR_target.csv"
    
  gtopdb:
    enabled: true
    http:
      base_url: "https://www.guidetopharmacology.org"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    batch_size: 50

# Ввод-вывод
io:
  input:
    path: "data/input/targets.csv"
    encoding: "utf-8"
    required_columns: ["target_chembl_id"]
    
  output:
    dir: "data/output/targets"
    format: "csv"
    csv:
      encoding: "utf-8"
      float_format: "%.6f"
      date_format: "%Y-%m-%dT%H:%M:%SZ"
      na_rep: ""
      line_terminator: "\n"

# Runtime настройки
runtime:
  workers: 4
  limit: null
  offset: 0
  dry_run: false
  date_tag: null
  dev_mode: false
  allow_incomplete_sources: false

# Логирование
logging:
  level: "INFO"
  file:
    enabled: true
    path: "data/logs/targets.log"
    max_size: "10MB"
    backup_count: 5
  console:
    enabled: true
    format: "text"
  structured: true

# Детерминизм
determinism:
  sort:
    by: ["target_chembl_id"]
    ascending: [true]
    na_position: "last"
  column_order:
    - "target_chembl_id"
    - "uniprot_id"
    - "unified_name"
    - "unified_organism"
    - "unified_tax_id"
    - "unified_target_type"
    - "has_chembl_data"
    - "has_uniprot_data"
    - "has_iuphar_data"
    - "has_gtopdb_data"
    - "multi_source_validated"
    - "extracted_at"

# Валидация
validation:
  enabled: true
  strict: false
  schema_validation: true
  data_quality_checks: true

# Постобработка
postprocess:
  qc:
    enabled: true
    fail_on: ["missing_target_chembl_id", "duplicate_primary_keys"]
    thresholds:
      missing_target_chembl_id: 0.0
      duplicate_primary_keys: 0.0
      no_source_data: 0.1
    detailed_report: true
    
  correlation:
    enabled: true
    methods: ["pearson", "spearman"]
    min_correlation: 0.5
    
  steps:
    - type: "unify_isoforms"
      description: "Unify protein isoforms and variants"
      rules:
        - prefer_canonical: true
        - merge_synonyms: true
    - type: "merge_sources"
      description: "Merge data from multiple sources"
      priority: ["chembl", "uniprot", "iuphar", "gtopdb"]
    - type: "validate_mappings"
      description: "Validate UniProt-ChEMBL mappings"
    - type: "deduplicate"
      description: "Remove duplicate entries"
      keys: ["target_chembl_id"]

# Нормализация
normalization:
  enabled: true
  uniprot_id_format: "standard"
  organism_format: "scientific_name"
  target_type_format: "standard"

# Качество данных
quality:
  profiles:
    default:
      enabled: true
      rules:
        - name: "valid_chembl_id"
          pattern: "^CHEMBL\\d+$"
        - name: "valid_uniprot_id"
          pattern: "^[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2}$"
        - name: "valid_taxonomy_id"
          min_value: 1

# Кэширование
cache:
  enabled: true
  dir: "data/cache/targets"
  ttl: 86400
  max_size: "1GB"

# Мониторинг и телеметрия
telemetry:
  enabled: false
  endpoint: null
  api_key: null
  batch_size: 100
  flush_interval: 30.0
