# Конфигурация v2 для targets pipeline
# Основана на унифицированном шаблоне config.template.yaml

# Метаданные пайплайна - основная информация о пайплайне
pipeline:
  name: "targets"                    # Имя пайплайна для идентификации
  version: "2.0.0"                  # Версия конфигурации
  entity_type: "targets"            # Тип сущности для обработки
  description: "ETL pipeline for target data from ChEMBL, UniProt, and IUPHAR"  # Описание назначения

# HTTP настройки
http:
  global:
    timeout_sec: 60.0
    retries:
      total: 5
      backoff_multiplier: 2.0
      backoff_max: 120.0
    rate_limit:
      max_calls: 5
      period: 15.0
    headers:
      Accept: "application/json"
      User-Agent: "bioactivity-data-acquisition/0.1.0"
    verify_ssl: true
    follow_redirects: true

# Источники данных - конфигурация источников для извлечения данных
sources:
  chembl:                             # ChEMBL API как основной источник
    enabled: true                     # Включен ли источник
    http:                             # HTTP настройки для ChEMBL
      base_url: "https://www.ebi.ac.uk/chembl/api/data"  # Базовый URL API
      timeout_sec: 60.0               # Таймаут для ChEMBL запросов
      retries:                        # Настройки повторных попыток
        total: 3                      # Количество попыток для ChEMBL
        backoff_multiplier: 1.5       # Множитель задержки
    batch_size: 1000                  # Размер батча для запросов (max 1000 для ChEMBL)
    max_compounds: null               # Максимум соединений (null = без ограничений)
    
  uniprot:                            # UniProt REST API для белковых данных
    enabled: true                     # Включен ли источник
    http:                             # HTTP настройки для UniProt
      base_url: "https://rest.uniprot.org"  # Базовый URL REST API
      timeout_sec: 30.0               # Таймаут для UniProt запросов
      retries:                        # Настройки повторных попыток
        total: 3                      # Количество попыток
        backoff_multiplier: 2.0       # Множитель задержки
    batch_size: 100                   # Размер батча для запросов
    mapping_enabled: true             # Включить маппинг UniProt-ChEMBL
    
  iuphar:                             # IUPHAR/BPS Guide to Pharmacology API
    enabled: true                     # Включен ли источник
    http:                             # HTTP настройки для IUPHAR
      base_url: "https://www.guidetopharmacology.org"  # Базовый URL API
      timeout_sec: 30.0               # Таймаут для IUPHAR запросов
      retries:                        # Настройки повторных попыток
        total: 3                      # Количество попыток
        backoff_multiplier: 2.0       # Множитель задержки
    batch_size: 50                    # Размер батча для запросов
    dictionary_path: "configs/dictionary/_target/_IUPHAR/_IUPHAR_target.csv"  # Путь к словарю IUPHAR
    
  gtopdb:                             # Guide to Pharmacology Database
    enabled: true                     # Включен ли источник
    http:                             # HTTP настройки для GtoP
      base_url: "https://www.guidetopharmacology.org"  # Базовый URL API
      timeout_sec: 30.0               # Таймаут для GtoP запросов
      retries:                        # Настройки повторных попыток
        total: 3                      # Количество попыток
        backoff_multiplier: 2.0       # Множитель задержки
    batch_size: 50                    # Размер батча для запросов

# Ввод-вывод
io:
  input:
    path: "data/input/targets.csv"
    encoding: "utf-8"
    required_columns: ["target_chembl_id"]
    
  output:
    dir: "data/output/targets"
    format: "csv"
    csv:
      encoding: "utf-8"
      float_format: "%.6f"
      date_format: "%Y-%m-%dT%H:%M:%SZ"
      na_rep: ""
      line_terminator: "\n"

# Runtime настройки
runtime:
  workers: 4
  limit: null
  offset: 0
  dry_run: false
  date_tag: null
  dev_mode: false
  allow_incomplete_sources: false

# Логирование
logging:
  level: "INFO"
  file:
    enabled: true
    path: "data/logs/targets.log"
    max_size: "10MB"
    backup_count: 5
  console:
    enabled: true
    format: "text"
  structured: true

# Детерминизм
determinism:
  sort:
    by: ["target_chembl_id"]
    ascending: [true]
    na_position: "last"
  column_order:
    # Основные идентификаторы и названия
    - "target_chembl_id"               # STRING: PK таргета из ChEMBL API /target, тип: STRING, валидация: NOT NULL, UNIQUE, pattern ^CHEMBL\d+$
    - "pref_name"                      # STRING: Предпочтительное название таргета, источник: ChEMBL, тип: STRING, валидация: nullable
    - "hgnc_name"                      # STRING: Название по HGNC, источник: HGNC, тип: STRING, валидация: nullable
    - "hgnc_id"                        # STRING: HGNC идентификатор, источник: HGNC, тип: STRING, валидация: nullable, pattern ^HGNC:\d+$
    - "target_type"                    # STRING: Тип таргета, источник: ChEMBL, тип: STRING, валидация: nullable
    - "tax_id"                         # INT: Таксономический ID, источник: ChEMBL, тип: INT, валидация: nullable, > 0
    - "species_group_flag"             # BOOL: Флаг группировки по видам, источник: ChEMBL, тип: BOOL, валидация: boolean
    - "target_components"              # TEXT: Компоненты таргета, источник: ChEMBL, тип: TEXT, валидация: nullable
    - "protein_classifications"        # TEXT: Классификация белка, источник: ChEMBL, тип: TEXT, валидация: nullable
    - "cross_references"               # TEXT: Перекрестные ссылки, источник: ChEMBL, тип: TEXT, валидация: nullable
    - "reaction_ec_numbers"            # TEXT: EC номера реакций, источник: ChEMBL, тип: TEXT, валидация: nullable
    
    # UniProt данные
    - "uniprot_id_primary"             # STRING: Первичный UniProt ID, источник: UniProt REST API, тип: STRING, валидация: nullable, UNIQUE
    - "uniProtkbId"                    # STRING: UniProtKB ID, источник: UniProt, тип: STRING, валидация: nullable
    - "secondaryAccessions"            # TEXT: Вторичные accession номера, источник: UniProt, тип: TEXT, валидация: nullable
    - "secondaryAccessionNames"        # TEXT: Названия вторичных accession, источник: UniProt, тип: TEXT, валидация: nullable
    - "recommendedName"                # STRING: Рекомендуемое название, источник: UniProt, тип: STRING, валидация: nullable
    - "protein_name_alt"               # STRING: Альтернативное название белка, источник: UniProt, тип: STRING, валидация: nullable
    - "geneName"                       # STRING: Название гена, источник: UniProt, тип: STRING, валидация: nullable
    - "gene_symbol_list"               # TEXT: Список символов генов, источник: UniProt, тип: TEXT, валидация: nullable
    - "organism"                       # STRING: Организм, источник: UniProt, тип: STRING, валидация: nullable
    - "taxon_id"                       # INT: Таксономический ID, источник: UniProt, тип: INT, валидация: nullable, > 0
    - "lineage_superkingdom"           # STRING: Суперцарство в линии, источник: UniProt, тип: STRING, валидация: nullable
    - "lineage_phylum"                 # STRING: Тип в линии, источник: UniProt, тип: STRING, валидация: nullable
    - "lineage_class"                  # STRING: Класс в линии, источник: UniProt, тип: STRING, валидация: nullable
    - "sequence_length"                # INT: Длина последовательности, источник: UniProt, тип: INT, валидация: nullable, > 0
    - "molecular_function"             # TEXT: Молекулярная функция, источник: UniProt, тип: TEXT, валидация: nullable
    - "cellular_component"             # TEXT: Клеточный компонент, источник: UniProt, тип: TEXT, валидация: nullable
    - "subcellular_location"           # TEXT: Субклеточная локализация, источник: UniProt, тип: TEXT, валидация: nullable
    - "topology"                       # TEXT: Топология, источник: UniProt, тип: TEXT, валидация: nullable
    - "transmembrane"                  # BOOL: Трансмембранный, источник: UniProt, тип: BOOL, валидация: boolean
    - "intramembrane"                  # BOOL: Внутримембранный, источник: UniProt, тип: BOOL, валидация: boolean
    - "glycosylation"                  # BOOL: Гликозилирование, источник: UniProt, тип: BOOL, валидация: boolean
    - "lipidation"                     # BOOL: Липидирование, источник: UniProt, тип: BOOL, валидация: boolean
    - "disulfide_bond"                 # BOOL: Дисульфидная связь, источник: UniProt, тип: BOOL, валидация: boolean
    - "modified_residue"               # BOOL: Модифицированный остаток, источник: UniProt, тип: BOOL, валидация: boolean
    - "phosphorylation"                # BOOL: Фосфорилирование, источник: UniProt, тип: BOOL, валидация: boolean
    - "acetylation"                    # BOOL: Ацетилирование, источник: UniProt, тип: BOOL, валидация: boolean
    - "ubiquitination"                 # BOOL: Убиквитинирование, источник: UniProt, тип: BOOL, валидация: boolean
    - "signal_peptide"                 # BOOL: Сигнальный пептид, источник: UniProt, тип: BOOL, валидация: boolean
    - "propeptide"                     # BOOL: Пропептид, источник: UniProt, тип: BOOL, валидация: boolean
    - "xref_ensembl"                   # TEXT: Ссылки на Ensembl, источник: UniProt, тип: TEXT, валидация: nullable
    - "xref_pdb"                       # TEXT: Ссылки на PDB, источник: UniProt, тип: TEXT, валидация: nullable
    - "xref_alphafold"                 # TEXT: Ссылки на AlphaFold, источник: UniProt, тип: TEXT, валидация: nullable
    - "family"                         # TEXT: Семейство, источник: UniProt, тип: TEXT, валидация: nullable
    - "SUPFAM"                         # TEXT: SUPFAM классификация, источник: UniProt, тип: TEXT, валидация: nullable
    - "PROSITE"                        # TEXT: PROSITE классификация, источник: UniProt, тип: TEXT, валидация: nullable
    - "InterPro"                       # TEXT: InterPro классификация, источник: UniProt, тип: TEXT, валидация: nullable
    - "Pfam"                           # TEXT: Pfam классификация, источник: UniProt, тип: TEXT, валидация: nullable
    - "PRINTS"                         # TEXT: PRINTS классификация, источник: UniProt, тип: TEXT, валидация: nullable
    - "TCDB"                           # TEXT: TCDB классификация, источник: UniProt, тип: TEXT, валидация: nullable
    - "GuidetoPHARMACOLOGY"            # TEXT: Guide to Pharmacology классификация, источник: UniProt, тип: TEXT, валидация: nullable
    - "reactions"                      # TEXT: Реакции, источник: UniProt, тип: TEXT, валидация: nullable
    - "reaction_ec_numbers"            # TEXT: EC номера реакций, источник: UniProt, тип: TEXT, валидация: nullable
    - "isoform_ids"                    # TEXT: ID изоформ, источник: UniProt, тип: TEXT, валидация: nullable
    - "isoform_names"                  # TEXT: Названия изоформ, источник: UniProt, тип: TEXT, валидация: nullable
    - "isoform_synonyms"               # TEXT: Синонимы изоформ, источник: UniProt, тип: TEXT, валидация: nullable
    - "uniprot_last_update"            # STRING: Последнее обновление UniProt, источник: UniProt, тип: DATE, валидация: nullable, ISO 8601
    - "uniprot_version"                # INT: Версия UniProt, источник: UniProt, тип: INT, валидация: nullable, > 0
    
    # IUPHAR/GtoP данные
    - "iuphar_target_id"               # INT: IUPHAR ID таргета, источник: IUPHAR API, тип: INT, валидация: nullable, UNIQUE
    - "iuphar_family_id"               # INT: IUPHAR ID семейства, источник: IUPHAR API, тип: INT, валидация: nullable
    - "iuphar_type"                    # STRING: Тип по IUPHAR, источник: IUPHAR API, тип: STRING, валидация: nullable
    - "iuphar_class"                   # STRING: Класс по IUPHAR, источник: IUPHAR API, тип: STRING, валидация: nullable
    - "iuphar_subclass"                # STRING: Подкласс по IUPHAR, источник: IUPHAR API, тип: STRING, валидация: nullable
    - "iuphar_chain"                   # STRING: Цепь по IUPHAR, источник: IUPHAR API, тип: STRING, валидация: nullable
    - "iuphar_name"                    # STRING: Название по IUPHAR, источник: IUPHAR API, тип: STRING, валидация: nullable
    - "iuphar_full_id_path"            # TEXT: Полный путь ID по IUPHAR, источник: IUPHAR API, тип: TEXT, валидация: nullable
    - "iuphar_full_name_path"          # TEXT: Полный путь названий по IUPHAR, источник: IUPHAR API, тип: TEXT, валидация: nullable
    - "gtop_target_id"                 # INT: GtoP ID таргета, источник: GtoP API, тип: INT, валидация: nullable
    - "gtop_synonyms"                  # TEXT: Синонимы по GtoP, источник: GtoP API, тип: TEXT, валидация: nullable
    - "gtop_natural_ligands_n"         # INT: Количество природных лигандов, источник: GtoP API, тип: INT, валидация: nullable, >= 0
    - "gtop_interactions_n"            # INT: Количество взаимодействий, источник: GtoP API, тип: INT, валидация: nullable, >= 0
    - "gtop_function_text_short"       # TEXT: Краткое описание функции, источник: GtoP API, тип: TEXT, валидация: nullable
    
   # Метаданные
    - "index"     
    - "pipeline_version"               # STRING: Версия пайплайна, источник: система, тип: STRING, валидация: NOT NULL                        # INT: Порядковый номер записи, тип: INT, валидация: NOT NULL, >= 0
    - "source_system"                 # STRING: Система-источник, источник: система, тип: STRING, валидация: NOT NULL
    - "chembl_release"                # STRING: Версия ChEMBL, источник: система, тип: STRING, валидация: nullable
    - "extracted_at"                  # STRING: Время извлечения данных, источник: система, тип: TIMESTAMP, валидация: NOT NULL, ISO 8601
    - "hash_row"                      # STRING: Хеш строки, источник: система, тип: STRING, валидация: NOT NULL, SHA256
    - "hash_business_key"             # STRING: Хеш бизнес-ключа, источник: система, тип: STRING, валидация: NOT NULL, SHA256

# Валидация - настройки проверки данных
validation:
  enabled: true                      # Включить валидацию
  strict: false                      # Строгий режим (останавливать при ошибках)
  schema_validation: true            # Валидация схемы данных
  data_quality_checks: true          # Проверки качества данных

# Постобработка - настройки обработки после извлечения
postprocess:
  qc:                               # Контроль качества
    enabled: true                    # Включить QC
    fail_on: ["missing_target_chembl_id", "duplicate_primary_keys"]  # Критические ошибки
    thresholds:                      # Пороговые значения для QC
      missing_target_chembl_id: 0.0 # Максимальный % отсутствующих target_chembl_id
      duplicate_primary_keys: 0.0   # Максимальный % дубликатов PK
      no_source_data: 0.1           # Максимальный % записей без данных источников
    detailed_report: true            # Детальный отчет QC
    
  correlation:                      # Корреляционный анализ
    enabled: true                    # Включить корреляцию
    methods: ["pearson", "spearman"] # Методы корреляции
    min_correlation: 0.5             # Минимальная корреляция
    
  steps:                            # Этапы постобработки
    - type: "unify_isoforms"        # Объединение изоформ
      description: "Unify protein isoforms and variants"
      rules:                         # Правила объединения
        - prefer_canonical: true     # Предпочитать канонические формы
        - merge_synonyms: true       # Объединять синонимы
    - type: "merge_sources"          # Объединение источников
      description: "Merge data from multiple sources"
      priority: ["chembl", "uniprot", "iuphar", "gtopdb"]  # Приоритет источников
    - type: "validate_mappings"      # Валидация маппингов
      description: "Validate UniProt-ChEMBL mappings"
    - type: "deduplicate"            # Дедупликация
      description: "Remove duplicate entries"
      keys: ["target_chembl_id"]     # Ключи дедупликации

# Нормализация - настройки нормализации данных
normalization:
  enabled: true                      # Включить нормализацию
  uniprot_id_format: "standard"     # Формат UniProt ID
  organism_format: "scientific_name"  # Формат названий организмов
  target_type_format: "standard"    # Формат типов таргетов

# Качество данных - профили контроля качества
quality:
  profiles:
    default:                        # Профиль по умолчанию
      enabled: true                  # Включен ли профиль
      rules:                        # Правила валидации
        - name: "valid_chembl_id"    # Валидация ChEMBL ID
          pattern: "^CHEMBL\\d+$"    # Регулярное выражение
        - name: "valid_uniprot_id"   # Валидация UniProt ID
          pattern: "^[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2}$"  # Формат UniProt accession
        - name: "valid_taxonomy_id"  # Валидация таксономического ID
          min_value: 1               # Минимальное значение

# Кэширование - настройки кэширования данных
cache:
  enabled: true                      # Включить кэширование
  dir: "data/cache/targets"         # Директория кэша
  ttl: 86400                        # Время жизни кэша в секундах (24 часа)
  max_size: "1GB"                   # Максимальный размер кэша

# Мониторинг и телеметрия - настройки сбора метрик
telemetry:
  enabled: false                     # Включить телеметрию
  endpoint: null                     # Endpoint для отправки метрик
  api_key: null                      # API ключ для аутентификации
  batch_size: 100                    # Размер батча для отправки
  flush_interval: 30.0               # Интервал отправки в секундах
