http:
  global:
    timeout_sec: 30.0
    retries:
      total: 5
      backoff_multiplier: 2.0
    headers:
      User-Agent: bioactivity-data-acquisition/0.1.0
sources:
  chembl:
    name: chembl
    enabled: true
    endpoint: document
    params:
      document_type: article
    pagination:
      page_param: page
      size_param: page_size
      size: 200
      max_pages: 1  # Ограничиваем для теста
    http:
      base_url: https://www.ebi.ac.uk/chembl/api/data
      timeout_sec: 60.0
      headers:
        Accept: application/json
        # Убираем Authorization для теста
      health_endpoint: "status"
  crossref:
    name: crossref
    enabled: false  # Отключаем для теста
  openalex:
    name: openalex
    enabled: false  # Отключаем для теста
  pubmed:
    name: pubmed
    enabled: false  # Отключаем для теста
  semantic_scholar:
    name: semantic_scholar
    enabled: false  # Отключаем для теста
io:
  input:
    documents_csv: data/input/documents.csv
  output:
    data_path: data/output/documents.csv
    qc_report_path: data/output/documents_qc_report.csv
    correlation_path: data/output/documents_correlation.csv
    format: csv
    csv:
      encoding: utf-8
      float_format: "%.3f"
      date_format: "%Y-%m-%dT%H:%M:%SZ"
runtime:
  workers: 1  # Минимум воркеров для теста
  limit: 10   # Ограничиваем количество документов
  dry_run: false
  date_tag: null
logging:
  level: INFO
  file:
    enabled: true
    path: logs/app.log
    max_bytes: 10485760
    backup_count: 10
    rotation_strategy: size
    retention_days: 14
    cleanup_on_start: false
  console:
    format: text
validation:
  strict: true
  qc:
    max_missing_fraction: 0.05
    max_duplicate_fraction: 0.01
determinism:
  sort:
    by:
      - document_chembl_id
      - title
    ascending:
      - true
      - true
    na_position: last
  column_order:
    - document_chembl_id
    - title
    - doi
    - journal
    - volume
    - issue
    - first_page
    - last_page
    - document_citation
    - source
    - retrieved_at
postprocess:
  qc:
    enabled: true
  correlation:
    enabled: true
  journal_normalization:
    enabled: true
    columns: ["journal", "pubmed_journal", "chembl_journal", "crossref_journal"]
  citation_formatting:
    enabled: true
    columns:
      journal: "journal"
      volume: "volume"
      issue: "issue"
      first_page: "first_page"
      last_page: "last_page"
