# Конфигурация для быстрого тестирования обработки документов
# Ограниченное количество записей и только ChEMBL для быстрой проверки

http:
  global:
    timeout_sec: 30.0
    retries:
      total: 3
      backoff_multiplier: 2.0
    headers:
      User-Agent: bioactivity-data-acquisition/0.1.0

sources:
  chembl:
    name: chembl
    enabled: true
    endpoint: document
    params:
      document_type: article
    pagination:
      page_param: page
      size_param: page_size
      size: 50  # Меньший размер страницы для тестирования
      max_pages: 1  # Только 1 страница для быстрого теста
    http:
      base_url: https://www.ebi.ac.uk/chembl/api/data
      timeout_sec: 60.0
      headers:
        Accept: application/json
        Authorization: "Bearer {chembl_api_token}"

  # Остальные источники отключены для быстрого тестирования
  crossref:
    name: crossref
    enabled: false

  openalex:
    name: openalex
    enabled: false

  pubmed:
    name: pubmed
    enabled: false

  semantic_scholar:
    name: semantic_scholar
    enabled: false

io:
  input:
    documents_csv: data/input/documents.csv
  output:
    dir: data/output/test
    format: csv
    csv:
      encoding: utf-8
      float_format: "%.3f"
      date_format: "%Y-%m-%dT%H:%M:%SZ"

runtime:
  workers: 2  # Меньше воркеров для тестирования
  limit: 10  # Ограничиваем до 10 документов для быстрого теста
  dry_run: false
  date_tag: "test"

logging:
  level: DEBUG  # Более подробное логирование для тестирования

validation:
  strict: false  # Менее строгая валидация для тестирования
  qc:
    max_missing_fraction: 0.1
    max_duplicate_fraction: 0.05

determinism:
  sort:
    by:
      - document_chembl_id
    ascending:
      - true
    na_position: last
  column_order:
    - document_chembl_id
    - title
    - doi
    - journal
    - citation

postprocess:
  qc:
    enabled: true
  correlation:
    enabled: false  # Отключаем для быстрого теста
  journal_normalization:
    enabled: true
    columns: ["journal"]
  citation_formatting:
    enabled: true
    columns:
      journal: "journal"
      volume: "volume"
      issue: "issue"
      first_page: "first_page"
      last_page: "last_page"
