http:
  global:
    timeout_sec: 30.0
    retries:
      total: 5
      backoff_multiplier: 2.0
    headers:
      User-Agent: bioactivity-data-acquisition/0.1.0
sources:
  chembl:
    name: chembl
    endpoint: activity
    params:
      activity_type: IC50
    pagination:
      page_param: page
      size_param: page_size
      size: 200
      max_pages: 10
    http:
      base_url: https://www.ebi.ac.uk/chembl/api/data
      timeout_sec: 30.0
      headers:
        Accept: application/json
        Authorization: "Bearer {chembl_api_token}"
  crossref:
    name: crossref
    params:
      query: chembl
      select: DOI,title
    pagination:
      page_param: cursor
      size_param: rows
      size: 100
      max_pages: 5
    http:
      base_url: https://api.crossref.org/works
      headers:
        Accept: application/json
        Crossref-Plus-API-Token: "{crossref_api_key}"
  openalex:
    name: openalex
    http:
      base_url: https://api.openalex.org/works
      headers:
        Accept: application/json
  pubmed:
    name: pubmed
    http:
      base_url: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi
      headers:
        Accept: application/json
  semantic_scholar:
    name: semantic_scholar
    http:
      base_url: https://api.semanticscholar.org/graph/v1/paper
      headers:
        Accept: application/json
io:
  input:
    documents_csv: data/input/documents.csv
  output:
    data_path: data/output/bioactivities.csv
    qc_report_path: data/output/qc_report.csv
    correlation_path: data/output/correlation.csv
    format: csv
    csv:
      encoding: utf-8
      float_format: "%.3f"
      date_format: "%Y-%m-%dT%H:%M:%SZ"
runtime:
  workers: 4
logging:
  level: INFO
validation:
  strict: true
  qc:
    max_missing_fraction: 0.05
    max_duplicate_fraction: 0.01
determinism:
  sort:
    by:
      - compound_id
      - target
    ascending:
      - true
      - true
    na_position: last
  column_order:
    - compound_id
    - target
    - activity_value
    - activity_unit
    - source
    - retrieved_at
    - smiles
transforms:
  unit_conversion:
    nM: 1.0
    uM: 1000.0
    pM: 0.001
postprocess:
  qc:
    enabled: true
  correlation:
    enabled: true
