# Конфигурация для полного извлечения данных активности из ChEMBL
# Включает все поля активности, нормализацию, валидацию и профили качества
#
# ВАЖНО: Система обеспечивает детерминированность и воспроизводимость результатов
# с фиксированным порядком строк/колонок, стабильной NA-политикой и атомарной записью

# Глобальные настройки HTTP-клиента
http:
  global:
    # Максимальное время ожидания ответа от сервера в секундах
    timeout_sec: 60.0
    # Настройки повторных попыток при неудачных запросах
    retries:
      # Общее количество попыток (включая первую)
      total: 5
      # Множитель для экспоненциальной задержки между попытками
      backoff_multiplier: 3.0
      # Настройки ограничения скорости запросов по умолчанию
      rate_limit:
        max_calls: 3
        period: 15.0      
      # Заголовки, отправляемые с каждым HTTP-запросом
      headers:
        Accept: application/json
        User-Agent: bioactivity-data-acquisition/0.1.0

# Конфигурация источника данных ChEMBL для активности
sources:
  chembl:
    # Уникальное имя источника
    name: chembl
    # API endpoint для получения данных активности
    endpoint: activity
    # Параметры запроса к API
    params:
      # Базовые параметры без фильтров (фильтры добавляются через CLI)
      format: json
    # Настройки пагинации
    pagination:
      # Параметр страницы
      page_param: offset
      # Параметр размера страницы
      size_param: limit
      # Размер страницы по умолчанию
      size: 1000
      # Максимальный размер страницы
      max_size: 1000
      # Максимальное количество страниц для обработки
      max_pages: null  # Без ограничений
    # HTTP настройки для ChEMBL
    http:
      # Базовый URL API ChEMBL
      base_url: https://www.ebi.ac.uk/chembl/api/data
      # Таймаут для запросов к ChEMBL
      timeout_sec: 60.0
      # Дополнительные заголовки для ChEMBL
      headers:
        Accept: application/json
        User-Agent: bioactivity-data-acquisition/0.1.0
        # Токен авторизации (заменяется на реальный токен)
        Authorization: "Bearer {chembl_api_token}"

# Настройки ввода-вывода данных
io:
  # Настройки входных данных
  input:
    # CSV файлы с фильтрами (опционально)
    assay_ids_csv: data/input/assay_ids_example.csv
    molecule_ids_csv: data/input/testitem_keys_example.csv
    target_ids_csv: data/input/target_ids_example.csv
    # Название колонки в CSV для чтения ID активностей (используется для фильтрации)
    activity_id_column: null  # null = используется текущая логика фильтрации
  # Настройки выходных данных
  output:
    # Директория для сохранения результатов
    dir: data/output/activity
    # Формат выходных файлов
    format: csv
    # Специфичные настройки для CSV формата
    csv:
      # Кодировка файла
      encoding: utf-8
      # Формат чисел с плавающей точкой (6 знаков после запятой для точности)
      float_format: "%.6f"
      # Формат даты и времени (ISO 8601)
      date_format: "%Y-%m-%dT%H:%M:%SZ"
  # Настройки кэширования
  cache:
    # Директория для кэша сырых данных
    raw_dir: data/cache/activity/raw
    # Включить кэширование
    enabled: true

# Настройки выполнения программы
runtime:
  # Количество параллельных воркеров для обработки данных
  workers: 4
  # Размер батча для извлечения и обработки активностей
  batch_size: 1000
  # Ограничение на количество обрабатываемых записей (null = без ограничений)
  limit: null
  # Режим тестирования (true = только симуляция, false = реальная обработка)
  dry_run: false
  # Тег даты для именования файлов (автоматическая генерация)
  date_tag: null

# Настройки логирования
logging:
  # Уровень детализации логов
  level: INFO
  # Настройки файлового логирования
  file:
    enabled: true
    path: data/logs/activity.log
    max_bytes: 10485760  # 10MB
    backup_count: 10
    rotation_strategy: size
    retention_days: 14
    cleanup_on_start: false
  # Настройки консольного логирования
  console:
    format: text

# Настройки валидации данных
validation:
  # Строгий режим валидации
  strict: true
  # Настройки контроля качества (QC)
  qc:
    # Максимальная доля пропущенных значений
    max_missing_fraction: 0.02
    # Максимальная доля дублирующихся записей
    max_duplicate_fraction: 0.005
    # Минимальная доля успешных связей с внешними ключами
    min_foreign_key_coverage: 0.95

# Настройки детерминизма для воспроизводимости результатов
determinism:
  # Настройки сортировки данных
  sort:
    # Поля для сортировки (в порядке приоритета)
    by:
      - activity_chembl_id  # ID активности в ChEMBL
      - assay_chembl_id           # Внешний ключ на assay
      - testitem_chembl_id        # Внешний ключ на testitem
    # Направление сортировки для каждого поля
    ascending:
      - true   # activity_chembl_id - по возрастанию
      - true   # assay_key - по возрастанию
      - true   # testitem_key - по возрастанию
    # Позиция для значений NULL/NA (last = в конце)
    na_position: last
  # Порядок колонок в выходном файле
  column_order:
    # Основные идентификаторы
    - activity_chembl_id      # ID активности в ChEMBL (PK)
    - assay_chembl_id               # Внешний ключ на assay
    - target_chembl_id              # Внешний ключ на target
    - document_chembl_id            # Внешний ключ на document
    
    - molecule_chembl_id      # Дублирование для диагностики
    
    # Опубликованные значения (копия из источника)
    - published_type          # Опубликованный тип активности
    - published_relation      # Опубликованное отношение
    - published_value         # Опубликованное значение
    - published_units         # Опубликованные единицы
    
    # Стандартизованные значения (основные для аналитики)
    - standard_type           # Стандартизованный тип активности
    - standard_relation       # Стандартизованное отношение
    - standard_value          # Стандартизованное значение
    - standard_units          # Стандартизованные единицы
    - standard_flag           # Флаг стандартизации
    
    # Интервальное представление для цензурированных данных
    - lower_bound             # Нижняя граница интервала
    - upper_bound             # Верхняя граница интервала
    - is_censored             # Флаг цензурирования
    
    # Дополнительные поля
    - pchembl_value           # pChEMBL значение
    - data_validity_comment   # Комментарий валидности данных
    - activity_comment        # Комментарий активности
    
    # BAO атрибуты
    - bao_endpoint            # BAO endpoint
    - bao_format              # BAO format
    - bao_label               # BAO label
    
    # Метаданные
    - retrieved_at            # Время получения данных
    - quality_flag            # Флаг качества
    - quality_reason          # Причина качества

# Настройки нормализации данных
normalization:
  # Правила преобразования отношений в интервалы
  relation_mapping:
    # Точные значения
    "=":
      lower_bound: "standard_value"
      upper_bound: "standard_value"
      is_censored: false
    # Больше или равно
    ">=":
      lower_bound: "standard_value"
      upper_bound: null
      is_censored: true
    ">":
      lower_bound: "standard_value"
      upper_bound: null
      is_censored: true
    # Меньше или равно
    "<=":
      lower_bound: null
      upper_bound: "standard_value"
      is_censored: true
    "<":
      lower_bound: null
      upper_bound: "standard_value"
      is_censored: true
  # Поддерживаемые типы активности для строгого профиля
  strict_activity_types:
    - IC50
    - Ki
  # Нежелательные комментарии активности
  rejected_activity_comments:
    - inconclusive
    - undetermined
    - unevaluated

# Настройки профилей качества
quality_profiles:
  # Строгий профиль качества
  strict:
    enabled: true
    # Обязательные поля
    required_fields:
      - assay_chembl_id
      - testitem_chembl_id
      - standard_type
      - standard_relation
      - standard_value
    # Ограничения на типы активности
    allowed_activity_types: "strict_activity_types"
    # Ограничения на отношения
    allowed_relations:
      - "="
    # Ограничения на комментарии валидности
    required_data_validity_comment: null  # Должен быть NULL
    # Ограничения на комментарии активности
    rejected_activity_comments: "rejected_activity_comments"
  
  # Умеренный профиль качества
  moderate:
    enabled: true
    # Обязательные поля (меньше требований)
    required_fields:
      - standard_type
      - standard_value
    # Разрешает неизвестные типы с пометкой
    allow_unknown_types: true
    # Разрешает неизвестные отношения с пометкой
    allow_unknown_relations: true
    # Разрешает определенные предупреждения валидности
    allowed_data_validity_warnings:
      - "Manually curated"
      - "Potential false positive"

# Настройки постобработки данных
postprocess:
  # Контроль качества данных
  qc:
    # Включить анализ качества данных
    enabled: true
    # Анализ распределений
    distribution_analysis:
      enabled: true
      fields:
        - standard_type
        - standard_units
        - standard_relation
        - is_censored
    # Анализ связей
    foreign_key_analysis:
      enabled: true
      # Пороги покрытия для внешних ключей
      coverage_thresholds:
        assay_key: 0.95
        target_key: 0.80
        document_key: 0.90
        testitem_key: 0.95
  # Генерация метаданных
  metadata:
    # Включить генерацию метаданных
    enabled: true
    # Поля для включения в метаданные
    fields:
      - chembl_release
      - extraction_url
      - extraction_ts
      - pipeline_version
      - rows_total
      - rows_filtered_strict
      - rows_filtered_moderate
      - rows_rejected
      - hash_of_source_listing

# =============================================================================
# ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ ДЛЯ API КЛЮЧЕЙ
# =============================================================================
# 
# Для использования API ключей установите следующие переменные окружения:
#
# Windows (PowerShell):
#   $env:CHEMBL_API_TOKEN = "your_chembl_token_here"
#
# Linux/macOS (bash):
#   export CHEMBL_API_TOKEN="your_chembl_token_here"
#
# ВАЖНО:
# - Система работает БЕЗ API ключей с ограничениями по rate limiting
# - При отсутствии API ключей используется graceful degradation
#
# Получить API ключ можно по ссылке:
# - ChEMBL: https://chembl.gitbook.io/chembl-interface-documentation/web-services/chembl-data-web-services
