# Конфигурация v2 для documents pipeline
# Основана на унифицированном шаблоне config.template.yaml

# Метаданные пайплайна
pipeline:
  name: "documents"
  version: "2.0.0"
  entity_type: "documents"
  description: "ETL pipeline for document metadata from multiple sources"

# HTTP настройки
http:
  global:
    timeout_sec: 60.0
    retries:
      total: 5
      backoff_multiplier: 2.0
      backoff_max: 120.0
    rate_limit:
      max_calls: 5
      period: 15.0
    headers:
      Accept: "application/json"
      User-Agent: "bioactivity-data-acquisition/0.1.0"
    verify_ssl: true
    follow_redirects: true

# Источники данных
sources:
  crossref:
    enabled: true
    http:
      base_url: "https://api.crossref.org"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    batch_size: 100
    max_requests_per_second: 10
    
  openalex:
    enabled: true
    http:
      base_url: "https://api.openalex.org"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    batch_size: 50
    max_requests_per_second: 5
    
  pubmed:
    enabled: true
    http:
      base_url: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    batch_size: 200
    max_requests_per_second: 3
    
  semantic_scholar:
    enabled: true
    http:
      base_url: "https://api.semanticscholar.org"
      timeout_sec: 30.0
      retries:
        total: 3
        backoff_multiplier: 2.0
    batch_size: 100
    max_requests_per_second: 5

# Ввод-вывод
io:
  input:
    path: "data/input/documents.csv"
    encoding: "utf-8"
    required_columns: ["document_chembl_id","doi", "pmid", "title"]
    
  output:
    dir: "data/output/documents"
    format: "csv"
    csv:
      encoding: "utf-8"
      float_format: "%.6f"
      date_format: "%Y-%m-%dT%H:%M:%SZ"
      na_rep: ""
      line_terminator: "\n"

# Runtime настройки
runtime:
  workers: 4
  limit: null
  offset: 0
  dry_run: false
  date_tag: null
  dev_mode: false
  allow_incomplete_sources: false

# Логирование
logging:
  level: "INFO"
  file:
    enabled: true
    path: "data/logs/documents.log"
    max_size: "10MB"
    backup_count: 5
  console:
    enabled: true
    format: "text"
  structured: true

# Детерминизм
determinism:
  sort:
    by: ["document_chembl_id", "doi", "pmid"]
    ascending: [true, true, true]
    na_position: "last"
  column_order:
    - index                   # ID документа 
    - extracted_at            # Время извлечения данных
    - hash_business_key       # Хеш бизнес-ключа (document_chembl_id)
    - hash_row                # Хеш всей строки для дедупликации
    # Основные поля документа (оригинальные из ChEMBL)
    - document_chembl_id      # ID документа в ChEMBL
    - document_pubmed_id      # PubMed идентификатор
    - document_classification # Классификация документа
    - referenses_on_previous_experiments  # Содержит ли документ внешние ссылки            # Номер первой страницы
    - original_experimental_document     # Является ли документ экспериментальным
    - document_citation       # Форматированная литературная ссылка
    - retrieved_at            # Время получения данных

    - pubmed_mesh_descriptors # MeSH дескрипторы из PubMed
    - pubmed_mesh_qualifiers  # MeSH квалификаторы из PubMed
    - pubmed_chemical_list    # Список химических веществ из PubMed
    - crossref_subject        # Предметная область из Crossref

    # Группа полей PMID из всех источников
    - chembl_pmid             # PMID из ChEMBL
    - crossref_pmid           # PMID из Crossref
    - openalex_pmid           # PMID из OpenAlex
    - pubmed_pmid             # PMID из PubMed
    - semantic_scholar_pmid   # PMID из Semantic Scholar
    
    # Группа полей названий статей из всех источников
    - chembl_title            # Название статьи из ChEMBL
    - crossref_title          # Название статьи из Crossref
    - openalex_title          # Название статьи из OpenAlex
    - pubmed_article_title    # Название статьи из PubMed
    - semantic_scholar_title  # Название статьи из Semantic Scholar
    
    # Группа полей аннотаций из всех источников
    - chembl_abstract            # Аннотация из ChEMBL
    - crossref_abstract          # Аннотация из Crossref
    - openalex_abstract          # Аннотация из OpenAlex
    - pubmed_abstract            # Аннотация из PubMed
    
    # Группа полей авторов из всех источников
    - chembl_authors             # Авторы из ChEMBL
    - crossref_authors           # Авторы из Crossref
    - openalex_authors           # Авторы из OpenAlex
    - pubmed_authors             # Авторы из PubMed
    - semantic_scholar_authors   # Авторы из Semantic Scholar
    
    # Группа полей DOI из всех источников
    - chembl_doi              # DOI из ChEMBL
    - crossref_doi            # DOI из Crossref
    - openalex_doi             # DOI из OpenAlex
    - pubmed_doi              # DOI из PubMed
    - semantic_scholar_doi    # DOI из Semantic Scholar
    
    # Группа полей типов публикации из всех источников
    - chembl_doc_type          # Тип документа из ChEMBL
    - crossref_doc_type       # Тип документа из Crossref
    - openalex_doc_type      # Тип документа из OpenAlex
    - openalex_crossref_doc_type  # Тип документа из OpenAlex    
    - pubmed_doc_type          # Тип публикации из PubMed
    - semantic_scholar_doc_type    # Типы публикации из Semantic Scholar
    
    # Группа полей ISSN из всех источников
    - chembl_issn             # ISSN из ChEMBL
    - crossref_issn           # ISSN из Crossref
    - openalex_issn           # ISSN из OpenAlex
    - pubmed_issn             # ISSN из PubMed
    - semantic_scholar_issn   # ISSN из Semantic Scholar
    
    # Группа полей названий журналов из всех источников
    - chembl_journal          # Название журнала из ChEMBL
    - crossref_journal        # Название журнала из Crossref
    - openalex_journal        # Название журнала из OpenAlex
    - pubmed_journal           # Название журнала из PubMed
    - semantic_scholar_journal  # Название журнала из Semantic Scholar
    
    # Группа полей годов издания из всех источников
    - chembl_year             # Год из ChEMBL
    - crossref_year           # Год из Crossref
    - openalex_year           # Год из OpenAlex
    - pubmed_year             # Год из PubMed
    #- openalex_year  # Год публикации из OpenAlex

    # Группа полей томов из всех источников
    - chembl_volume           # Том из ChEMBL
    - crossref_volume         # Том из Crossref
    - openalex_volume         # Том из OpenAlex
    - pubmed_volume           # Том из PubMed
    
    # Группа полей выпусков из всех источников
    - chembl_issue            # Номер выпуска из ChEMBL
    - crossref_issue          # Номер выпуска из Crossref
    - openalex_issue          # Номер выпуска из OpenAlex
    - pubmed_issue            # Номер выпуска из PubMed
    
    # Группа полей первых страниц из всех источников
    - crossref_first_page     # Первая страница из Crossref
    - openalex_first_page     # Первая страница из OpenAlex
    - pubmed_first_page       # Начальная страница из PubMed
    
    # Группа полей последних страниц из всех источников
    - crossref_last_page      # Последняя страница из Crossref
    - openalex_last_page      # Последняя страница из OpenAlex
    - pubmed_last_page        # Конечная страница из PubMed
    
    # Группа полей ошибок из всех источников
    - chembl_error            # Ошибка из ChEMBL
    - crossref_error          # Ошибка из Crossref
    - openalex_error          # Ошибка из OpenAlex
    - pubmed_error            # Ошибка из PubMed
    - semantic_scholar_error  # Ошибка из Semantic Scholar

    # Поля из PubMed (расширенные)
    - pubmed_year_completed   # Год завершения из PubMed
    - pubmed_month_completed  # Месяц завершения из PubMed
    - pubmed_day_completed    # День завершения из PubMed
    - pubmed_year_revised     # Год пересмотра из PubMed
    - pubmed_month_revised    # Месяц пересмотра из PubMed
    - pubmed_day_revised      # День пересмотра из PubMed
    - publication_date        # Дата публикации (определяется на основе полей PubMed)
    - document_sortorder      # Порядок сортировки документов (определяется на основе pubmed_issn, publication_date и index)

    # Поля валидации данных из различных источников

    - valid_doi               # Валидное значение DOI
    - valid_journal           # Валидное значение журнала
    - valid_year              # Валидное значение года
    - valid_volume            # Валидное значение тома
    - valid_issue             # Валидное значение номера выпуска
    - invalid_doi             # Флаг невалидности DOI
    - invalid_journal         # Флаг невалидности журнала   
    - invalid_year            # Флаг невалидности года
    - invalid_volume          # Флаг невалидности тома
    - invalid_issue           # Флаг невалидности номера выпуска    

# Валидация
validation:
  enabled: true
  strict: false
  schema_validation: true
  data_quality_checks: true

# Постобработка
postprocess:
  qc:
    enabled: true
    fail_on: ["missing_doi", "missing_title"]
    thresholds:
      missing_doi: 0.1
      missing_title: 0.05
    detailed_report: true
    
  correlation:
    enabled: true
    methods: ["pearson", "spearman"]
    min_correlation: 0.5
    
  steps:
    - type: "merge_sources"
      description: "Merge data from multiple sources"
      priority: ["crossref", "openalex", "pubmed", "semantic_scholar"]
    - type: "doi_fallback"
      description: "Use DOI as fallback identifier"
    - type: "author_normalization"
      description: "Normalize author names and affiliations"
    - type: "journal_normalization"
      description: "Normalize journal names"
    - type: "citation_formatting"
      description: "Format citation data"

# Нормализация
normalization:
  enabled: true
  doi_format: "standard"
  author_format: "last_first"
  date_format: "iso"

# Качество данных
quality:
  profiles:
    default:
      enabled: true
      rules:
        - name: "valid_doi"
          pattern: "^10\\.\\d+/[^\\s]+$"
        - name: "valid_pmid"
          pattern: "^\\d+$"
        - name: "non_empty_title"
          min_length: 10

# Кэширование
cache:
  enabled: true
  dir: "data/cache/documents"
  ttl: 86400
  max_size: "1GB"

# Мониторинг и телеметрия
telemetry:
  enabled: false
  endpoint: null
  api_key: null
  batch_size: 100
  flush_interval: 30.0
