# Конфигурация для полной обработки target данных со всеми источниками
# Включает ChEMBL, UniProt, IUPHAR - все источники обязательны
# 
# ВАЖНО: Все источники (ChEMBL, UniProt, IUPHAR) являются обязательными.
# Система требует наличия данных от всех источников для корректной работы.
# В dev/test режиме можно отключить источники через dev_mode: true
#
# Глобальные настройки HTTP-клиента
http:
  global:
    # Максимальное время ожидания ответа от сервера в секундах
    timeout_sec: 60.0
    # Настройки повторных попыток при неудачных запросах
    retries:
      # Общее количество попыток (включая первую)
      total: 10
      # Множитель для экспоненциальной задержки между попытками
      backoff_multiplier: 3.0
    # Настройки ограничения скорости запросов по умолчанию
    rate_limit:
      max_calls: 5
      period: 15.0
    # Заголовки, отправляемые с каждым HTTP-запросом
    headers:
      Accept: application/json
      User-Agent: bioactivity-data-acquisition/0.1.0

# Конфигурация источников данных (все обязательны)
sources:
  # ChEMBL - база данных химических соединений и биологической активности
  chembl:
    # Уникальное имя источника
    name: chembl
    # Включен ли источник (обязательно)
    enabled: true
    # API endpoint для получения targets
    endpoint: target
    # Параметры запроса к API
    params:
      # Формат ответа
      format: json
      # Включаемые поля для детальной информации
      include: "protein_classifications,protein_classification,cross_references,target_components,target_component_synonyms,target_component_xrefs"
    # Переопределения HTTP настроек
    http:
      # Базовый URL API ChEMBL
      base_url: https://www.ebi.ac.uk/chembl/api/data
      # Таймаут для запросов к ChEMBL
      timeout_sec: 60.0
      # Дополнительные заголовки для ChEMBL
      headers:
        # Токен авторизации (заменяется на реальный токен)
        Authorization: "Bearer {chembl_api_token}"
      # Настройки повторных попыток для ChEMBL
      retries:
        # Общее количество попыток
        total: 5
        # Множитель задержки между попытками
        backoff_multiplier: 2.0

  # UniProt - база данных белковых последовательностей
  uniprot:
    # Уникальное имя источника
    name: uniprot
    # Включен ли источник (обязательно)
    enabled: true
    # Параметры для UniProt
    params:
      # Настройки маппинга ChEMBL -> UniProt
      mapping_service_url: https://rest.uniprot.org/idmapping  # Базовый URL UniProt ID Mapping API
      mapping_file: null         # Путь к файлу маппинга (если есть)
      mapping_columns:
        chembl_id: "target_chembl_id"
        uniprot_id: "uniprot_id"
    # Переопределения HTTP настроек
    http:
      # Базовый URL API UniProt
      base_url: https://rest.uniprot.org
      # Таймаут для запросов к UniProt
      timeout_sec: 60.0
      # Настройки повторных попыток для UniProt
      retries:
        # Общее количество попыток
        total: 3
        # Множитель задержки между попытками
        backoff_multiplier: 1.0

  # IUPHAR - база данных фармакологических рецепторов
  iuphar:
    # Уникальное имя источника
    name: iuphar
    # Включен ли источник (обязательно)
    enabled: true
    # Параметры для IUPHAR
    params:
      # Использовать CSV словари (предпочтительно)
      use_csv: true
      # Путь к словарям IUPHAR
      dictionary_path: "configs/dictionary/_target/_IUPHAR/"
      # Файлы словарей
      family_file: "_IUPHAR_family.csv"
      target_file: "_IUPHAR_target.csv"
    # Переопределения HTTP настроек
    http:
      # Базовый URL API IUPHAR (fallback)
      base_url: https://www.guidetopharmacology.org/services
      # Таймаут для запросов к IUPHAR
      timeout_sec: 30.0
      # Настройки повторных попыток для IUPHAR
      retries:
        # Общее количество попыток
        total: 3
        # Множитель задержки между попытками
        backoff_multiplier: 1.0

  # GtoPdb - Guide to Pharmacology database enrichment
  gtopdb:
    # Уникальное имя источника
    name: gtopdb
    # Включен ли источник (возможность отключения обогащения)
    enabled: true
    # Параметры для GtoPdb
    params:
      # API endpoints
      base_url: https://www.guidetopharmacology.org
      api_version: services
    # Переопределения HTTP настроек
    http:
      # Базовый URL API GtoPdb
      base_url: https://www.guidetopharmacology.org/services
      # Таймаут для запросов к GtoPdb
      timeout_sec: 30.0
      # Настройки повторных попыток для GtoPdb
      retries:
        # Общее количество попыток
        total: 3
        # Множитель задержки между попытками
        backoff_multiplier: 1.5
      # Настройки rate limiting
      rate_limit:
        # Запросов в секунду
        rps: 1.0
        # Всплеск запросов
        burst: 2
    # Настройки circuit breaker
    circuit_breaker:
      # Порог количества ошибок для открытия circuit breaker
      failure_threshold: 5
      # Время блокировки в секундах (5 минут)
      holdoff_seconds: 300

# Настройки ввода-вывода данных
io:
  # Настройки входных данных
  input:
    # Путь к CSV файлу с идентификаторами targets
    target_ids_csv: data/input/target.csv
    # Название колонки в CSV для чтения ID targets (по умолчанию: target_chembl_id)
    target_id_column: target_chembl_id
  # Настройки выходных данных
  output:
    # Директория для сохранения результатов
    dir: data/output/target
    # Формат выходных файлов
    format: csv
    # Специфичные настройки для CSV формата
    csv:
      # Кодировка файла
      encoding: utf-8
      # Формат чисел с плавающей точкой (3 знака после запятой)
      float_format: "%.3f"
      # Формат даты и времени (ISO 8601)
      date_format: "%Y-%m-%dT%H:%M:%SZ"
      # Представление отсутствующих значений
      na_rep: ""
      # Разделитель строк
      line_terminator: null
    # Специфичные настройки для Parquet формата
    parquet:
      # Сжатие данных
      compression: snappy

# Настройки выполнения программы
runtime:
  # Количество параллельных воркеров для обработки данных
  workers: 4
  # Ограничение на количество обрабатываемых записей (null = без ограничений)
  limit: null
  # Режим тестирования (true = только симуляция, false = реальная обработка)
  dry_run: false
  # Режим разработки (позволяет отключить источники для тестирования)
  dev_mode: false
  # Разрешить неполные источники (только в dev режиме)
  allow_incomplete_sources: false
  # Тег даты для именования файлов (автоматическая генерация)
  # date_tag будет сгенерирован автоматически

# Настройки логирования
logging:
  # Уровень детализации логов (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: INFO
  # Настройки файлового логирования
  file:
    enabled: true
    path: data/logs/target.log
    max_bytes: 10485760  # 10MB
    backup_count: 10
    rotation_strategy: size
    retention_days: 14

# Настройки детерминизма для воспроизводимости результатов
determinism:
  # Настройки сортировки данных
  sort:
    # Поля для сортировки (в порядке приоритета)
    by:
      - target_chembl_id  # ID target в ChEMBL
    # Направление сортировки для каждого поля
    ascending:
      - true   # target_chembl_id - по возрастанию
    # Позиция для значений NULL/NA (last = в конце)
    na_position: last
  # Порядок колонок в выходном файле
  column_order:
    # Основные поля target (ключи и идентификаторы)
    - target_chembl_id         # ID target в ChEMBL
    - pref_name                # Предпочтительное название
    - component_description    # Описание компонента
    - component_id             # ID компонента
    - relationship             # Тип связи
    - gene                     # Ген
    - uniprot_id               # UniProt ID из ChEMBL
    - mapping_uniprot_id       # UniProt ID из маппинга
    - chembl_alternative_name  # Альтернативное название из ChEMBL
    - ec_code                  # EC код
    - hgnc_name                # HGNC название
    - hgnc_id                  # HGNC ID
    - target_type              # Тип target
    - tax_id                   # Таксономический ID
    - species_group_flag       # Флаг группы видов
    - target_components        # Компоненты target
    - protein_classifications  # Классификации белков
    - cross_references         # Перекрестные ссылки
    - reaction_ec_numbers      # EC номера реакций
    
    # UniProt enrichment fields
    - uniprot_id_primary       # Основной UniProt ID
    - uniProtkbId              # UniProtKB ID
    - secondaryAccessions      # Вторичные акцессии
    - secondaryAccessionNames  # Названия вторичных акцессий
    - recommendedName          # Рекомендуемое название
    - protein_name_alt         # Альтернативные названия белков
    - geneName                 # Название гена
    - gene_symbol_list         # Список символов генов
    - organism                 # Организм
    - taxon_id                 # Таксономический ID
    - lineage_superkingdom     # Суперцарство
    - lineage_phylum           # Тип
    - lineage_class            # Класс
    - sequence_length          # Длина последовательности
    - molecular_function       # Молекулярная функция
    - cellular_component       # Клеточный компонент
    - subcellular_location     # Субклеточная локализация
    - topology                 # Топология
    - transmembrane            # Трансмембранный
    - intramembrane            # Внутримембранный
    - glycosylation            # Гликозилирование
    - lipidation               # Липидирование
    - disulfide_bond           # Дисульфидные связи
    - modified_residue         # Модифицированные остатки
    - phosphorylation          # Фосфорилирование
    - acetylation              # Ацетилирование
    - ubiquitination           # Убиквитинирование
    - signal_peptide           # Сигнальный пептид
    - propeptide               # Пропептид
    - xref_ensembl             # Ensembl ссылки
    - xref_pdb                 # PDB ссылки
    - xref_alphafold           # AlphaFold ссылки
    - family                   # Семейство
    - SUPFAM                   # SUPFAM
    - PROSITE                  # PROSITE
    - InterPro                 # InterPro
    - Pfam                     # Pfam
    - PRINTS                   # PRINTS
    - TCDB                     # TCDB
    - GuidetoPHARMACOLOGY      # Guide to PHARMACOLOGY
    - reactions                # Реакции
    - reaction_ec_numbers      # EC номера реакций
    - isoform_ids              # ID изоформ
    - isoform_names            # Названия изоформ
    - isoform_synonyms         # Синонимы изоформ
    - uniprot_last_update      # Последнее обновление UniProt
    - uniprot_version          # Версия UniProt
    - pipeline_version         # Версия пайплайна
    - timestamp_utc            # Временная метка UTC
    
    # IUPHAR enrichment fields
    - iuphar_target_id         # IUPHAR target ID
    - iuphar_family_id         # IUPHAR family ID
    - iuphar_type              # IUPHAR тип
    - iuphar_class             # IUPHAR класс
    - iuphar_subclass          # IUPHAR подкласс
    - iuphar_chain             # IUPHAR цепочка
    - iuphar_name              # IUPHAR название
    - iuphar_full_id_path      # Полный путь ID
    - iuphar_full_name_path    # Полный путь названий
    - gtop_target_id           # GtoP target ID
    - gtop_synonyms            # GtoP синонимы
    - gtop_natural_ligands_n   # Количество природных лигандов
    - gtop_interactions_n      # Количество взаимодействий
    - gtop_function_text_short # Краткое описание функции

# Настройки постобработки данных
postprocess:
  # Контроль качества данных
  qc:
    # Включить анализ качества данных
    enabled: true
  # Корреляционный анализ между источниками
  correlation:
    # Включить анализ корреляций
    enabled: true

# ChEMBL retry configuration
chembl_retry:
  # Включить retry логику для ChEMBL API
  enable: true
  # Коэффициент сжатия батча при таймауте (0.5 = уменьшить в 2 раза)
  shrink_factor: 0.5
  # Минимальный размер батча
  min_size: 1
  # Количество повторных попыток для единичных запросов
  single_timeout_retries: 2
  # Задержка между повторными попытками (секунды)
  single_timeout_delay: 0.5

# UniProt mapping configuration
uniprot_mapping:
  # Включить batch маппинг ChEMBL->UniProt
  enable_batch_mapping: true
  # Максимальное время ожидания batch job (секунды)
  batch_job_timeout: 1200
  # Максимальное количество попыток проверки статуса
  max_status_polls: 30
  # Интервал между проверками статуса (секунды)
  status_poll_interval: 2.0

# =============================================================================
# ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ ДЛЯ API КЛЮЧЕЙ
# =============================================================================
# 
# Для использования API ключей установите следующие переменные окружения:
#
# Windows (PowerShell):
#   $env:CHEMBL_API_TOKEN = "your_chembl_token_here"
#
# Linux/macOS (bash):
#   export CHEMBL_API_TOKEN="your_chembl_token_here"
#
# ВАЖНО:
# - Система работает БЕЗ API ключей с ограничениями по rate limiting
# - При отсутствии API ключей используется graceful degradation
# - ChEMBL API работает без токена, но с ограничениями по запросам
# - UniProt и IUPHAR работают без API ключей
#
# Получить API ключи можно по следующим ссылкам:
# - ChEMBL: https://chembl.gitbook.io/chembl-interface-documentation/web-services/chembl-data-web-services