# Конфигурация для полной обработки документов со всеми источниками
# Включает все доступные API и максимальную детализацию

http:
  global:
    timeout_sec: 60.0  # Увеличенный таймаут для всех запросов
    retries:
      total: 10
      backoff_multiplier: 3.0
    headers:
      User-Agent: bioactivity-data-acquisition/0.1.0

sources:
  chembl:
    name: chembl
    enabled: true
    endpoint: document
    params:
      document_type: article
    pagination:
      page_param: page
      size_param: page_size
      size: 200
      max_pages: 50  # Больше страниц для полной обработки
    http:
      base_url: https://www.ebi.ac.uk/chembl/api/data
      timeout_sec: 120.0  # Увеличенный таймаут для ChEMBL
      headers:
        Accept: application/json
        Authorization: "Bearer {chembl_api_token}"

  crossref:
    name: crossref
    enabled: true
    params:
      query: chembl
      select: DOI,title
    pagination:
      page_param: cursor
      size_param: rows
      size: 100
      max_pages: 20  # Больше страниц для полной обработки
    http:
      base_url: https://api.crossref.org/works
      timeout_sec: 60.0
      headers:
        Accept: application/json
        Crossref-Plus-API-Token: "{crossref_api_key}"

  openalex:
    name: openalex
    enabled: true
    http:
      base_url: https://api.openalex.org/works
      timeout_sec: 60.0
      headers:
        Accept: application/json

  pubmed:
    name: pubmed
    enabled: true
    rate_limit:
      max_calls: 5  # Увеличенный лимит при наличии API ключа
      period: 1.0
    http:
      base_url: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/
      timeout_sec: 120.0
      headers:
        Accept: application/json
        User-Agent: bioactivity-data-acquisition/0.1.0
        api_key: "{PUBMED_API_KEY}"
      retries:
        total: 15
        backoff_multiplier: 4.0

  semantic_scholar:
    name: semantic_scholar
    enabled: true  # Включен для полной обработки
    rate_limit:
      max_calls: 2  # Увеличенный лимит при наличии API ключа
      period: 60.0  # 1 минута
    http:
      base_url: https://api.semanticscholar.org/graph/v1/paper
      timeout_sec: 120.0
      headers:
        Accept: application/json
        x-api-key: "{SEMANTIC_SCHOLAR_API_KEY}"
      retries:
        total: 20
        backoff_multiplier: 5.0

io:
  input:
    documents_csv: data/input/documents.csv
  output:
    dir: data/output/full
    format: csv
    csv:
      encoding: utf-8
      float_format: "%.3f"
      date_format: "%Y-%m-%dT%H:%M:%SZ"

runtime:
  workers: 8  # Больше воркеров для полной обработки
  limit: null  # Без ограничений
  dry_run: false

logging:
  level: INFO

validation:
  strict: true
  qc:
    max_missing_fraction: 0.02  # Более строгие требования
    max_duplicate_fraction: 0.005

determinism:
  sort:
    by:
      - document_chembl_id
      - title
      - doi
    ascending:
      - true
      - true
      - true
    na_position: last
  column_order:
    - document_chembl_id
    - title
    - doi
    - journal
    - volume
    - issue
    - first_page
    - last_page
    - citation
    - source
    - retrieved_at
    - chembl_title
    - chembl_doi
    - crossref_title
    - openalex_title
    - pubmed_pmid
    - semantic_scholar_pmid

postprocess:
  qc:
    enabled: true
  correlation:
    enabled: true
  journal_normalization:
    enabled: true
  citation_formatting:
    enabled: true
