http:
  global:
    timeout_sec: 30.0
    retries:
      total: 5
      backoff_multiplier: 2.0
    headers:
      User-Agent: bioactivity-data-acquisition/0.1.0
sources:
  chembl:
    name: chembl
    enabled: true
    endpoint: document
    params:
      document_type: article
    pagination:
      page_param: page
      size_param: page_size
      size: 200
      max_pages: 10
    http:
      base_url: https://www.ebi.ac.uk/chembl/api/data
      timeout_sec: 60.0  # Увеличиваем таймаут для ChEMBL
      headers:
        Accept: application/json
        Authorization: "Bearer {chembl_api_token}"
      health_endpoint: "status"  # Используем специальный эндпоинт для проверки здоровья
  crossref:
    name: crossref
    enabled: true
    params:
      query: chembl
      select: DOI,title
    pagination:
      page_param: cursor
      size_param: rows
      size: 100
      max_pages: 5
    http:
      base_url: https://api.crossref.org/works
      timeout_sec: 30.0
      headers:
        Accept: application/json
        Crossref-Plus-API-Token: "{crossref_api_key}"
      # health_endpoint не указан - будет использоваться base_url для проверки здоровья
  openalex:
    name: openalex
    enabled: true
    http:
      base_url: https://api.openalex.org/works
      timeout_sec: 30.0
      headers:
        Accept: application/json
      # health_endpoint не указан - будет использоваться base_url для проверки здоровья
  pubmed:
    name: pubmed
    enabled: true
    rate_limit:
      max_calls: 2  # Консервативный лимит: 2 запроса в секунду (без API ключа лимит 3/сек)
      period: 1.0
    http:
      base_url: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/
      timeout_sec: 60.0  # Увеличиваем таймаут для медленных запросов
      headers:
        Accept: application/json
        User-Agent: bioactivity-data-acquisition/0.1.0
        api_key: "{PUBMED_API_KEY}"  # API ключ для увеличения лимитов до 10/сек
      retries:
        total: 10  # Больше попыток для обработки rate limiting
        backoff_multiplier: 3.0  # Более агрессивный backoff
  # Semantic Scholar включен с оптимизированными настройками rate limiting
  semantic_scholar:
    name: semantic_scholar
    enabled: true  # Всегда включен
    rate_limit:
      max_calls: 1   # 1 запрос в 10 секунд (реальные лимиты API: максимум 2 запроса подряд)
      period: 10.0   # Период в секундах (10 секунд - консервативный лимит для стабильности)
    http:
      base_url: https://api.semanticscholar.org/graph/v1/paper
      timeout_sec: 60.0
      headers:
        Accept: application/json
        x-api-key: "{SEMANTIC_SCHOLAR_API_KEY}"  # API ключ для увеличения лимитов
      retries:
        total: 15
        backoff_multiplier: 5.0
io:
  input:
    documents_csv: data/input/documents.csv
  output:
    data_path: data/output/full/documents.csv
    qc_report_path: data/output/full/documents_qc_report.csv
    correlation_path: data/output/full/documents_correlation.csv
    format: csv
    csv:
      encoding: utf-8
      float_format: "%.3f"
      date_format: "%Y-%m-%dT%H:%M:%SZ"
runtime:
  workers: 4
  limit: null  # Ограничение количества документов для обработки (null = без ограничений)
  dry_run: false  # Режим тестирования без сохранения
  date_tag: null  # Автоматически генерируется если null
logging:
  level: INFO
  file:
    enabled: true
    path: logs/app.log
    max_bytes: 10485760  # 10MB
    backup_count: 10
    rotation_strategy: size
    retention_days: 14
    cleanup_on_start: false
  console:
    format: text
validation:
  strict: true
  qc:
    max_missing_fraction: 0.05
    max_duplicate_fraction: 0.01
determinism:
  sort:
    by:
      - document_chembl_id
      - title
    ascending:
      - true
      - true
    na_position: last
  column_order:
    - document_chembl_id
    - title
    - doi
    - journal
    - volume
    - issue
    - first_page
    - last_page
    - document_citation
    - source
    - retrieved_at
# transforms не нужны для документов
postprocess:
  qc:
    enabled: true
  correlation:
    enabled: true
  journal_normalization:
    enabled: true
    columns: ["journal", "pubmed_journal", "chembl_journal", "crossref_journal"]
  citation_formatting:
    enabled: true
    columns:
      journal: "journal"
      volume: "volume"
      issue: "issue"
      first_page: "first_page"
      last_page: "last_page"
