project:
  name: "Bioactivity Data Acquisition"
  version: "0.1.0"
io:
  output:
    data_path: "data/output/bioactivities.csv"
    qc_report_path: "data/output/qc_report.csv"
    correlation_path: "data/output/correlation.csv"
runtime:
  log_level: "INFO"
http:
  retry:
    max_tries: 3
    backoff_multiplier: 1.5
sources:
  chembl:
    name: "chembl"
    url: "https://example.com/activities"
    pagination:
      param: "page"
      size_param: "page_size"
      size: 100
      max_pages: 2
postprocess:
  qc:
    enabled: true
    correlation: true
secrets:
  required: []
  optional: []
