version: 1
disable_existing_loggers: false

# Платформо-специфичные настройки
# Windows: использует более простой формат для совместимости
# Unix/Linux: полный формат с контекстом

formatters:
  console:
    # Универсальный формат для всех платформ
    format: "%(asctime)s %(levelname)s %(name)s — %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    format: "%(asctime)s %(levelname)s %(name)s %(message)s run_id:%(run_id)s stage:%(stage)s trace_id:%(trace_id)s"
    datefmt: "%Y-%m-%dT%H:%M:%S"

filters:
  redact_secrets:
    (): library.logging_setup.RedactSecretsFilter
  add_context:
    (): library.logging_setup.AddContextFilter
  safe_formatting:
    (): library.logging_setup.SafeFormattingFilter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: console
    filters: [redact_secrets, add_context, safe_formatting]
    stream: ext://sys.stderr
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: json
    # Платформо-специфичные настройки файлов
    # Windows: более короткие имена файлов
    # Unix: стандартные имена
    filters: [redact_secrets, add_context, safe_formatting]
    filename: logs/app.log
    when: midnight
    interval: 1
    backupCount: 7
    encoding: utf-8

loggers:
  "":
    level: INFO
    handlers: [console, file]
    propagate: false
  library:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  library.clients:
    level: INFO
    handlers: [console, file]
    propagate: false
  library.etl:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  library.documents:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  requests:
    level: WARNING
    handlers: [console, file]
    propagate: false
  urllib3:
    level: CRITICAL
    handlers: []
    propagate: false
  urllib3.connectionpool:
    level: CRITICAL
    handlers: []
    propagate: false
  backoff:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file]