site_name: Bioactivity Data Acquisition
site_url: https://satorykono.github.io/bioactivity_data_acquisition/
repo_url: https://github.com/SatoryKono/bioactivity_data_acquisition
repo_name: SatoryKono/bioactivity_data_acquisition
edit_uri: edit/main/docs/
strict: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  language: ru

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
          options:
            show_source: true
            docstring_style: google
            separate_signature: true
  - mermaid2
  - table-reader

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list
  - tables

nav:
  - Обзор: index.md
  - Getting started: getting-started.md
  - Архитектура: architecture.md
  - Конфигурация: configuration.md
  - CLI: cli.md
  - Validation: validation.md
  - Источники данных: data-sources.md
  - Артефакты выгрузки: outputs.md
  - API limits: api-limits.md
  - Разработка: development.md
  - Качество и тесты: quality.md
  - CI/CD: ci.md
  - Эксплуатация: operations.md
  - Руководство по контрибьюшену: contributing.md
  - Релизы и изменения: changelog.md
  - FAQ: faq.md
  - Глоссарий: glossary.md
  - Руководства:
      - Туториалы: tutorials/index.md
      - Обогащение документов (E2E): tutorials/e2e_documents.md
      - Полный пайплайн (E2E): tutorials/e2e_pipeline.md
  - API Reference:
      - Library: reference/index.md

