site_name: Bioactivity Data Acquisition
site_url: https://satorykono.github.io/bioactivity_data_acquisition/
repo_url: https://github.com/SatoryKono/bioactivity_data_acquisition
repo_name: SatoryKono/bioactivity_data_acquisition
edit_uri: edit/main/docs/
strict: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  language: ru

plugins:
  - search:
      lang: ru
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths:
            - src
          options:
            docstring_style: google
            docstring_section_style: spacy
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            show_object_full_path: false
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            separate_signature: true
            line_length: 80
            merge_init_into_class: true
            show_if_no_docstring: false
  - mermaid2
  - table-reader
  - htmlproofer:
      raise_error: true
      ignore_urls:
        - 'https://pandera.readthedocs.io/*'
        - 'https://www.semanticscholar.org/*'
      anchors: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list
  - tables

nav:
  - Обзор: index.md
  - Пайплайны:
      - Documents: pipelines/documents.md
      - Testitem: pipelines/testitem.md
      - Assay: pipelines/assay.md
      - Activity: pipelines/activity.md
      - Target: pipelines/target.md
  - Конфигурация:
      - Обзор: reference/configuration/index.md
      - Sources: configuration/sources.md
  - Контракты и правила:
      - Extraction Contract: extraction-contract.md
      - Normalization: normalization.md
      - Enrichment: enrichment.md
      - Validation: validation.md
      - Quality (QC): qc.md
      - Persistence & Determinism: persistence.md
  - CLI и логирование:
      - CLI: cli.md
      - Logging & Metrics: logging.md
  - Тесты и артефакты:
      - Tests Policy: tests.md
      - Output Artifacts: output-artifacts.md
      - Star-Schema: star-schema.md
      - Non-Goals: non-goals.md
  - Справочник:
      - Обзор: reference/index.md
      - CLI:
          - Обзор: reference/cli/index.md
          - Команда pipeline: reference/cli/pipeline.md
          - Команда get-document-data: reference/cli/get-document-data.md
      - API:
          - Обзор: reference/api/index.md
          - Клиенты: reference/api/clients.md
          - ETL: reference/api/etl.md
          - Схемы: reference/api/schemas.md
  - Объяснения:
      - Обзор: explanations/index.md
      - Архитектура: explanations/architecture.md
      - Решения дизайна: explanations/design-decisions.md
      - Чувствительность к регистру: explanations/case-sensitivity.md
  - Туториалы:
      - Обзор: tutorials/index.md
      - Быстрый старт: tutorials/quickstart.md
      - Полный пайплайн (E2E): tutorials/e2e-pipeline.md
      - Обогащение документов (E2E): tutorials/e2e-documents.md
  - Дополнительно:
      - Источники данных: data-sources.md
      - API limits: api-limits.md
      - CI/CD: ci.md
      - FAQ: faq.md
      - Глоссарий: glossary.md
      - Релизы и изменения: changelog.md

