# Конфигурация постпроцессинга документов
# Пример конфигурации для полного цикла обработки документов

# Настройки постпроцессинга
postprocess:
  documents:
    # Приоритет источников для разрешения конфликтов
    # Порядок: от высшего к низшему приоритету
    priority_sources: ["chembl", "pubmed", "crossref", "openalex", "semantic_scholar"]
    
    # Настройки нормализации DOI
    doi:
      normalize: true                    # Включить нормализацию DOI
      key_field: "doi_key"              # Имя поля для нормализованного DOI
      remove_prefixes:                  # Префиксы для удаления
        - "https://doi.org/"
        - "http://doi.org/"
        - "doi:"
      lowercase: true                   # Привести к нижнему регистру
      trim_whitespace: true             # Обрезать пробелы
    
    # Настройки нормализации журналов
    journal:
      normalize_titlecase: false        # НЕ использовать title case (оставляем lower+trim+punct_strip)
      mapping_dict_path: "configs/journal_map.yaml"  # Обновлено: путь в configs/
      remove_articles: true             # Удалять артикли (the, a, an)
      normalize_abbreviations: true     # Расшифровывать сокращения
      unicode_normalization: "NFC"      # Unicode нормализация
    
    # Настройки дедупликации
    dedupe:
      # Поля для дедупликации (в порядке приоритета)
      key_fields: ["document_chembl_id", "doi_key", "pmid_key"]
      
      # Настройки похожести заголовков
      title_similarity:
        method: "token_sort_ratio"      # Алгоритм сравнения: token_sort_ratio, ratio, partial_ratio
        threshold: 92                   # Порог похожести (0-100)
        case_sensitive: false           # Учитывать регистр при сравнении
        remove_punctuation: true        # Удалять пунктуацию при сравнении
      
      # Стратегия разрешения конфликтов
      conflict_resolution:
        strategy: "priority_based"      # Стратегия: priority_based, most_complete, latest
        log_conflicts: true             # Логировать конфликты
        conflict_report_path: "reports/conflicts.json"  # Путь к отчету о конфликтах
    
    # Настройки обогащения полей
    enrichment:
      # Вычисление производных полей
      derived_fields:
        journal_normalized: true        # Нормализованное название журнала
        year_str: true                  # Строковое представление года
        title_norm: true                # Нормализованный заголовок
        document_citation: true         # Форматированная литературная ссылка
      
      # Настройки форматирования цитат
      citation_formatting:
        format: "standard"              # Формат: standard, apa, mla, chicago
        include_pages: true             # Включать страницы в цитату
        page_format: "p. {first}-{last}"  # Формат страниц
        max_page_range: 10000           # Максимальный диапазон страниц
    
    # Настройки экспорта
    export:
      # Форматы вывода
      format: ["csv", "parquet"]        # Список форматов: csv, parquet, json
      
      # Настройки CSV
      csv:
        index: false                    # Не включать индекс в CSV
        encoding: "utf-8"               # Кодировка файла
        # Порядок колонок (должен соответствовать determinism.column_order)
        columns: [
          "index",
          "document_chembl_id",
          "document_pubmed_id",
          "document_classification",
          "referenses_on_previous_experiments",
          "original_experimental_document",
          "document_citation",
          "retrieved_at",
          "pubmed_mesh_descriptors",
          "pubmed_mesh_qualifiers",
          "pubmed_chemical_list",
          "crossref_subject",
          "chembl_pmid",
          "crossref_pmid",
          "openalex_pmid",
          "pubmed_pmid",
          "semantic_scholar_pmid",
          "chembl_title",
          "crossref_title",
          "openalex_title",
          "pubmed_article_title",
          "semantic_scholar_title",
          "chembl_abstract",
          "crossref_abstract",
          "openalex_abstract",
          "pubmed_abstract",
          "chembl_authors",
          "crossref_authors",
          "openalex_authors",
          "pubmed_authors",
          "semantic_scholar_authors",
          "chembl_doi",
          "crossref_doi",
          "openalex_doi",
          "pubmed_doi",
          "semantic_scholar_doi",
          "chembl_doc_type",
          "crossref_doc_type",
          "openalex_doc_type",
          "openalex_crossref_doc_type",
          "pubmed_doc_type",
          "semantic_scholar_doc_type",
          "chembl_issn",
          "crossref_issn",
          "openalex_issn",
          "pubmed_issn",
          "semantic_scholar_issn",
          "chembl_journal",
          "crossref_journal",
          "openalex_journal",
          "pubmed_journal",
          "semantic_scholar_journal",
          "chembl_year",
          "crossref_year",
          "openalex_year",
          "pubmed_year",
          "chembl_volume",
          "crossref_volume",
          "openalex_volume",
          "pubmed_volume",
          "chembl_issue",
          "crossref_issue",
          "openalex_issue",
          "pubmed_issue",
          "crossref_first_page",
          "openalex_first_page",
          "pubmed_first_page",
          "crossref_last_page",
          "openalex_last_page",
          "pubmed_last_page",
          "chembl_error",
          "crossref_error",
          "openalex_error",
          "pubmed_error",
          "semantic_scholar_error",
          "pubmed_year_completed",
          "pubmed_month_completed",
          "pubmed_day_completed",
          "pubmed_year_revised",
          "pubmed_month_revised",
          "pubmed_day_revised",
          "valid_doi",
          "valid_journal",
          "valid_year",
          "valid_volume",
          "valid_issue",
          "invalid_doi",
          "invalid_journal",
          "invalid_year",
          "invalid_volume",
          "invalid_issue"
        ]
        # Политика обработки NA значений
        na_policy: 
          string: ""                    # Пустая строка для строковых полей
          int: null                     # null для целых чисел
          float: null                   # null для чисел с плавающей точкой
          bool: null                    # null для булевых значений
        float_format: "%.3f"            # Формат чисел с плавающей точкой
        date_format: "%Y-%m-%dT%H:%M:%SZ"  # Формат дат (ISO 8601)
        line_terminator: "\n"           # Разделитель строк
      
      # Настройки Parquet
      parquet:
        engine: "pyarrow"               # Движок: pyarrow, fastparquet
        compression: "gzip"             # Сжатие: gzip, snappy, brotli, lz4
        coerce_timestamps: "ms"         # Приведение временных меток к миллисекундам
        preserve_index: false           # Сохранять индекс
        schema_validation: true         # Валидация схемы при записи
      
      # Настройки сортировки
      sort_by: ["document_chembl_id", "doi_key"]  # Поля для сортировки
      sort_ascending: [true, true]      # Направление сортировки для каждого поля
      na_position: "last"               # Позиция NA значений: first, last
    
    # Настройки контроля качества
    qc:
      # Включить QC проверки
      enabled: true
      
      # Пороги для остановки при ошибках
      fail_on:
        - "missing_required_keys"       # Отсутствие обязательных ключей
        - "duplicate_primary_keys"      # Дублирующиеся первичные ключи
        - "invalid_doi_fraction"        # Превышение доли невалидных DOI
        - "invalid_journal_fraction"    # Превышение доли невалидных журналов
        - "year_out_of_range"           # Годы вне допустимого диапазона
        - "page_logic_errors"           # Ошибки в логике страниц
      
      # Пороги качества (доли от 0.0 до 1.0)
      thresholds:
        missing_document_chembl_id: 0.0      # 0% - абсолютно недопустимо
        missing_doi_and_pmid: 0.05           # 5% - максимум без DOI/PMID
        missing_title: 0.02                  # 2% - максимум без заголовка
        duplicate_document_chembl_id: 0.0    # 0% - дубли недопустимы
        invalid_doi_fraction: 0.1            # 10% - максимум невалидных DOI
        invalid_journal_fraction: 0.15       # 15% - максимум невалидных журналов
        year_out_of_range: 0.01              # 1% - максимум лет вне диапазона
        page_logic_errors: 0.05              # 5% - максимум ошибок страниц
      
      # Путь к QC отчету
      report_path: "out/qc/documents_qc.json"
      
      # Расширенные QC проверки
      enhanced:
        enabled: true                   # Включить расширенные проверки
        correlation_analysis: true      # Анализ корреляций между полями
        anomaly_detection: true         # Детекция аномалий
        statistical_checks: true        # Статистические проверки
      
      # Pandera валидация
      pandera:
        enabled: true                   # Включить валидацию схемы Pandera
        strict_mode: true               # Строгий режим валидации
        coerce_types: true              # Автоматическое приведение типов
        schema_path: "src/library/schemas/document_output_schema.py"  # Путь к схеме
    
    # Настройки логирования
    logging:
      level: "INFO"                     # Уровень логирования: DEBUG, INFO, WARNING, ERROR, CRITICAL
      file: "logs/documents_post.log"   # Путь к файлу логов
      json: true                        # JSON формат логов (python-json-logger formatter)
      console: true                     # Вывод в консоль
      max_file_size: "10MB"             # Максимальный размер файла лога
      backup_count: 5                   # Количество резервных файлов
      
      # Поля контекста для логирования
      context_fields:
        - "run_id"                      # Уникальный идентификатор запуска
        - "step"                        # Текущий шаг постпроцессинга
        - "elapsed_ms"                  # Время выполнения в миллисекундах
        - "rows_processed"              # Количество обработанных строк
        - "source_stats"                # Статистика по источникам данных

# Настройки детерминизма (должны соответствовать export.sort_by и export.columns)
determinism:
  sort:
    by: ["document_chembl_id", "doi_key"]  # Поля для сортировки
    ascending: [true, true]                # Направление сортировки
    na_position: "last"                    # Позиция NA значений
  column_order: [
    "index",
    "document_chembl_id",
    "document_pubmed_id",
    "document_classification",
    "referenses_on_previous_experiments",
    "original_experimental_document",
    "document_citation",
    "retrieved_at",
    "pubmed_mesh_descriptors",
    "pubmed_mesh_qualifiers",
    "pubmed_chemical_list",
    "crossref_subject",
    "chembl_pmid",
    "crossref_pmid",
    "openalex_pmid",
    "pubmed_pmid",
    "semantic_scholar_pmid",
    "chembl_title",
    "crossref_title",
    "openalex_title",
    "pubmed_article_title",
    "semantic_scholar_title",
    "chembl_abstract",
    "crossref_abstract",
    "openalex_abstract",
    "pubmed_abstract",
    "chembl_authors",
    "crossref_authors",
    "openalex_authors",
    "pubmed_authors",
    "semantic_scholar_authors",
    "chembl_doi",
    "crossref_doi",
    "openalex_doi",
    "pubmed_doi",
    "semantic_scholar_doi",
    "chembl_doc_type",
    "crossref_doc_type",
    "openalex_doc_type",
    "openalex_crossref_doc_type",
    "pubmed_doc_type",
    "semantic_scholar_doc_type",
    "chembl_issn",
    "crossref_issn",
    "openalex_issn",
    "pubmed_issn",
    "semantic_scholar_issn",
    "chembl_journal",
    "crossref_journal",
    "openalex_journal",
    "pubmed_journal",
    "semantic_scholar_journal",
    "chembl_year",
    "crossref_year",
    "openalex_year",
    "pubmed_year",
    "chembl_volume",
    "crossref_volume",
    "openalex_volume",
    "pubmed_volume",
    "chembl_issue",
    "crossref_issue",
    "openalex_issue",
    "pubmed_issue",
    "crossref_first_page",
    "openalex_first_page",
    "pubmed_first_page",
    "crossref_last_page",
    "openalex_last_page",
    "pubmed_last_page",
    "chembl_error",
    "crossref_error",
    "openalex_error",
    "pubmed_error",
    "semantic_scholar_error",
    "pubmed_year_completed",
    "pubmed_month_completed",
    "pubmed_day_completed",
    "pubmed_year_revised",
    "pubmed_month_revised",
    "pubmed_day_revised",
    "valid_doi",
    "valid_journal",
    "valid_year",
    "valid_volume",
    "valid_issue",
    "invalid_doi",
    "invalid_journal",
    "invalid_year",
    "invalid_volume",
    "invalid_issue"
  ]
  lowercase_columns: []                 # Колонки для приведения к нижнему регистру (пустой список = не применять)

# Настройки вывода (дополняют postprocess.documents.export)
output:
  format: "csv"                         # Основной формат вывода: csv, parquet
  csv:
    encoding: "utf-8"                   # Кодировка CSV файлов
    float_format: "%.3f"                # Формат чисел с плавающей точкой
    date_format: "%Y-%m-%dT%H:%M:%SZ"   # Формат дат
    na_rep: ""                          # Представление NA значений
    line_terminator: "\n"               # Разделитель строк
  parquet:
    engine: "pyarrow"                   # Движок Parquet
    compression: "gzip"                 # Сжатие
    coerce_timestamps: "ms"             # Приведение временных меток

