logging:
  level: INFO
etl:
  strict_validation: true
  output_dir: data/output
sources:
  chembl:
    base_url: https://www.ebi.ac.uk/chembl/api/data
    rate_limit_per_minute: 30
  pubmed:
    base_url: https://eutils.ncbi.nlm.nih.gov/entrez/eutils
  semscholar:
    base_url: https://api.semanticscholar.org/graph/v1
  crossref:
    base_url: https://api.crossref.org
  openalex:
    base_url: https://api.openalex.org
