extends:
  - ../pipelines/document.yaml

sources:
  pubmed:
    enabled: false
    tool: "test-tool"
    email: "test@example.com"
    api_key: "dummy-pubmed-key"
  crossref:
    enabled: false
    mailto: "test@example.com"
  openalex:
    enabled: false
  semantic_scholar:
    enabled: false
  chembl:
    enabled: false

postprocess:
  qc:
    enabled: false

qc:
  enabled: false
