"""Stub for structlog.stdlib module."""

from __future__ import annotations

from typing import Any, Callable

def add_logger_name(logger: Any, method_name: str, event_dict: dict[str, Any]) -> dict[str, Any]: ...
def add_log_level(logger: Any, method_name: str, event_dict: dict[str, Any]) -> dict[str, Any]: ...

class BoundLogger:
    def info(self, *args: Any, **kwargs: Any) -> None: ...
    def error(self, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, *args: Any, **kwargs: Any) -> None: ...
    def debug(self, *args: Any, **kwargs: Any) -> None: ...

class LoggerFactory:
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
