from __future__ import annotations

from typing import Any

def clear_contextvars() -> None: ...
def bind_contextvars(**kwargs: Any) -> Any: ...
def merge_contextvars(logger: Any, method_name: str, event_dict: dict[str, Any]) -> dict[str, Any]: ...
