"""Type stubs for click."""

from collections.abc import Callable
from typing import Any

def get_current_context() -> Any: ...

class ParameterSource:
    COMMANDLINE: str = ...
    ENVIRONMENT: str = ...
    DEFAULT: str = ...
    PROMPT: str = ...

